## 2026 NFL Fantasy WR Rankings Project Part 1 - Data Scraping and Cleaning

### Imports

In [95]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
import nflreadpy as nfl

In [3]:
years = list(range(2020,2026))

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
pd.set_option('display.max_rows', None)

### Scraping from NFL API

In [6]:
weekly_stats = nfl.load_player_stats(years)

In [96]:
weekly = weekly_stats.to_pandas()

In [8]:
print(list(weekly.columns))

['player_id', 'player_name', 'player_display_name', 'position', 'position_group', 'headshot_url', 'season', 'week', 'season_type', 'game_id', 'team', 'opponent_team', 'completions', 'attempts', 'passing_yards', 'passing_tds', 'passing_interceptions', 'sacks_suffered', 'sack_yards_lost', 'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards', 'passing_yards_after_catch', 'passing_first_downs', 'passing_epa', 'passing_cpoe', 'passing_2pt_conversions', 'pacr', 'passing_10', 'passing_16', 'passing_20', 'passing_40', 'carries', 'rushing_yards', 'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost', 'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions', 'rushing_10', 'rushing_12', 'rushing_20', 'rushing_40', 'receptions', 'targets', 'receiving_yards', 'receiving_tds', 'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards', 'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa', 'receiving_2pt_conversions', 'receiving_10', 'receiving_16', 'receiving_20', 'receiving_40', 'racr', 'target_share', 'air_yards_share', 'wopr', 'special_teams_tds', 'def_tackles_solo', 'def_tackles_with_assist', 'def_tackle_assists', 'def_tackles_for_loss', 'def_tackles_for_loss_yards', 'def_fumbles_forced', 'def_sacks', 'def_sack_yards', 'def_qb_hits', 'def_interceptions', 'def_interception_yards', 'def_pass_defended', 'def_tds', 'def_fumbles', 'def_safeties', 'misc_yards', 'fumble_recovery_own', 'fumble_recovery_yards_own', 'fumble_recovery_opp', 'fumble_recovery_yards_opp', 'fumble_recovery_tds', 'penalties', 'penalty_yards', 'fumbles_forced_by_opp', 'fumbles_not_forced', 'fumbles_out_of_bounds', 'fumbles_total', 'fumbles_lost_total', 'punt_returns', 'punt_return_yards', 'kickoff_returns', 'kickoff_return_yards', 'fg_made', 'fg_att', 'fg_missed', 'fg_blocked', 'fg_long', 'fg_pct', 'fg_made_0_19', 'fg_made_20_29', 'fg_made_30_39', 'fg_made_40_49', 'fg_made_50_59', 'fg_made_60_', 'fg_missed_0_19', 'fg_missed_20_29', 'fg_missed_30_39', 'fg_missed_40_49', 'fg_missed_50_59', 'fg_missed_60_', 'fg_made_list', 'fg_missed_list', 'fg_blocked_list', 'fg_made_distance', 'fg_missed_distance', 'fg_blocked_distance', 'pat_made', 'pat_att', 'pat_missed', 'pat_blocked', 'pat_pct', 'gwfg_made', 'gwfg_att', 'gwfg_missed', 'gwfg_blocked', 'gwfg_distance', 'pt_att', 'pt_blocked', 'pt_long', 'pt_yards', 'pt_inside_20', 'pt_out_of_bounds', 'pt_downed', 'pt_touchback', 'pt_fair_caught', 'pt_returned', 'pt_return_yards', 'pt_return_tds', 'pt_net_yards', 'fantasy_points', 'fantasy_points_ppr']

**Cleaning:**
- Filter to just regular season with 'season_type'
- Standardize names (remove Jr., Sr., II, III)
- Need to aggregate weekly stats into seasons

### Data Cleaning and Manipulation

In [97]:
weekly = weekly[weekly['season_type'] == 'REG']

In [98]:
weekly['player_display_name'] = (
    weekly['player_display_name']
    .str.replace(r'\s+(Jr\.?|Sr\.?|II|III|IV|V)$', '', regex=True)
)

In [99]:
metrics_to_average = [ 
    'completions', 'attempts', 'passing_yards', 'passing_tds', 'passing_interceptions', 'sacks_suffered', 
    'sack_yards_lost', 'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards', 'passing_yards_after_catch', 
    'passing_first_downs', 'passing_2pt_conversions', 'passing_10', 'passing_16', 'passing_20', 'passing_40', 
    'passing_epa', 'passing_cpoe', 'carries', 'rushing_yards', 'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost', 
    'rushing_first_downs', 'rushing_2pt_conversions', 'rushing_10', 'rushing_12', 
    'rushing_20', 'rushing_40', 'rushing_epa','receptions', 'targets', 'receiving_yards', 'receiving_tds', 
    'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards', 'receiving_yards_after_catch', 
    'receiving_first_downs', 'receiving_2pt_conversions', 'receiving_10', 'receiving_16', 
    'receiving_20', 'receiving_40', 'receiving_epa' 'target_share', 'air_yards_share', 'wopr', 
    'special_teams_tds', 'punt_returns', 'punt_return_yards', 'kickoff_returns', 
    'kickoff_return_yards', 'fantasy_points', 'fantasy_points_ppr'
]

In the above, some stats like passing_cpoe (completion percentage over expectation) would ideally be recalculated on season sums, but I don't have the necessary data to do that so I am performing a simple average as a proxy.

I am not including the following columns below because they are essentially calculations made using other fields already in my dataset, which will have a high correlation.
- PACR: passing yards / passing air yards
- RACR: receiving yards / receiving air yards

In [100]:
# 1. Clean up the columns: Identify which metrics are actually in your weekly DataFrame
valid_metrics = [col for col in metrics_to_average if col in weekly.columns]

# 2. Automatically find and convert any numeric columns that are currently stored as 'str'
for col in valid_metrics:
    # If the column is numeric-like but pandas thinks it's a string, convert it to float
    if weekly[col].dtype in ['string', 'object', 'str']:
        # errors='coerce' turns non-numeric values (like empty strings or lists) into NaN
        weekly[col] = pd.to_numeric(weekly[col], errors='coerce')

In [101]:
numeric_metrics = []
for col in valid_metrics:
    if pd.api.types.is_numeric_dtype(weekly[col]):
        numeric_metrics.append(col)
    else:
        print(f"Skipping non-numeric column: {col} (dtype: {weekly[col].dtype})")

In [102]:
# 4. Build the aggregation dictionary for the numeric columns only
agg_dict = {f"{metric}_pg": (metric, 'mean') for metric in numeric_metrics}

In [103]:
seasonal = weekly.groupby(['player_display_name', 'season']).agg(
    **agg_dict,
    games_played=('week', 'count')
).reset_index()

In [15]:
seasonal[seasonal['player_display_name'] == 'Brian Robinson']

,player_display_name,season,completions_pg,attempts_pg,passing_yards_pg,passing_tds_pg,passing_interceptions_pg,sacks_suffered_pg,sack_yards_lost_pg,sack_fumbles_pg,sack_fumbles_lost_pg,passing_air_yards_pg,passing_yards_after_catch_pg,passing_first_downs_pg,passing_2pt_conversions_pg,passing_10_pg,passing_16_pg,passing_20_pg,passing_40_pg,passing_epa_pg,passing_cpoe_pg,carries_pg,rushing_yards_pg,rushing_tds_pg,rushing_fumbles_pg,rushing_fumbles_lost_pg,rushing_first_downs_pg,rushing_2pt_conversions_pg,rushing_10_pg,rushing_12_pg,rushing_20_pg,rushing_40_pg,rushing_epa_pg,receptions_pg,targets_pg,receiving_yards_pg,receiving_tds_pg,receiving_fumbles_pg,receiving_fumbles_lost_pg,receiving_air_yards_pg,receiving_yards_after_catch_pg,receiving_first_downs_pg,receiving_2pt_conversions_pg,receiving_10_pg,receiving_16_pg,receiving_20_pg,receiving_40_pg,air_yards_share_pg,wopr_pg,special_teams_tds_pg,punt_returns_pg,punt_return_yards_pg,kickoff_returns_pg,kickoff_return_yards_pg,fantasy_points_pg,fantasy_points_ppr_pg,games_played
1376,Brian Robinson,2022,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,17.083333,66.416667,0.166667,0.166667,0.000000,4.083333,0.000000,1.500000,0.916667,0.166667,0.000000,-0.519616,0.750000,1.000000,5.000000,0.083333,0.000000,0.0,-0.916667,6.000000,0.250000,0.0,0.250000,0.083333,0.000000,0.000000,-0.004087,0.050633,0.0,0.0,0.0,0.000000,0.000000,8.641667,9.391667,12
1377,Brian Robinson,2023,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,11.866667,48.866667,0.333333,0.200000,0.133333,3.133333,0.066667,1.266667,0.866667,0.266667,0.000000,-1.409103,2.400000,2.866667,24.533333,0.266667,0.066667,0.0,-3.666667,27.333333,1.000000,0.0,0.866667,0.733333,0.533333,0.133333,-0.012869,0.109573,0.0,0.0,0.0,0.000000,0.000000,10.806667,13.206667,15
1378,Brian Robinson,2024,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,13.357143,57.071429,0.571429,0.142857,0.142857,3.357143,0.000000,1.357143,0.857143,0.285714,0.142857,-0.862933,1.428571,1.785714,11.357143,0.000000,0.000000,0.0,-1.642857,12.785714,0.285714,0.0,0.285714,0.071429,0.071429,0.000000,-0.009559,0.082987,0.0,0.0,0.0,0.000000,0.000000,9.985714,11.414286,14
1379,Brian Robinson,2025,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,5.411765,23.529412,0.117647,0.000000,0.000000,1.176471,0.000000,0.588235,0.352941,0.000000,0.000000,-0.047974,0.470588,0.705882,1.470588,0.000000,0.000000,0.0,0.000000,2.058824,0.058824,0.0,0.000000,0.000000,0.000000,0.000000,-0.000047,0.031288,0.0,0.0,0.0,0.764706,22.235294,3.205882,3.676471,17

In [59]:
seasonal.columns

Index(['player_display_name', 'season', 'completions_pg', 'attempts_pg',
       'passing_yards_pg', 'passing_tds_pg', 'passing_interceptions_pg',
       'sacks_suffered_pg', 'sack_yards_lost_pg', 'sack_fumbles_pg',
       'sack_fumbles_lost_pg', 'passing_air_yards_pg',
       'passing_yards_after_catch_pg', 'passing_first_downs_pg',
       'passing_2pt_conversions_pg', 'passing_10_pg', 'passing_16_pg',
       'passing_20_pg', 'passing_40_pg', 'passing_epa_pg', 'passing_cpoe_pg',
       'carries_pg', 'rushing_yards_pg', 'rushing_tds_pg',
       'rushing_fumbles_pg', 'rushing_fumbles_lost_pg',
       'rushing_first_downs_pg', 'rushing_2pt_conversions_pg', 'rushing_10_pg',
       'rushing_12_pg', 'rushing_20_pg', 'rushing_40_pg', 'rushing_epa_pg',
       'receptions_pg', 'targets_pg', 'receiving_yards_pg', 'receiving_tds_pg',
       'receiving_fumbles_pg', 'receiving_fumbles_lost_pg',
       'receiving_air_yards_pg', 'receiving_yards_after_catch_pg',
       'receiving_first_downs_pg', 'receiving_2pt_conversions_pg',
       'receiving_10_pg', 'receiving_16_pg', 'receiving_20_pg',
       'receiving_40_pg', 'air_yards_share_pg', 'wopr_pg',
       'special_teams_tds_pg', 'punt_returns_pg', 'punt_return_yards_pg',
       'kickoff_returns_pg', 'kickoff_return_yards_pg', 'fantasy_points_pg',
       'fantasy_points_ppr_pg', 'games_played'],
      dtype='str')

**Teammate Dataset**

The cleaning is complete. I am now creating duplicates of these statistical dataframes because a part of my model will include the stats from the player's best teammate.

In [104]:
teammate_seasonal = seasonal.copy()

In [105]:
teammate_seasonal.columns = 'Teammate_' + teammate_seasonal.columns

In [106]:
passing_cols = ['Teammate_completions_pg', 'Teammate_attempts_pg',
       'Teammate_passing_yards_pg', 'Teammate_passing_tds_pg',
       'Teammate_passing_interceptions_pg', 'Teammate_sacks_suffered_pg',
       'Teammate_sack_yards_lost_pg', 'Teammate_sack_fumbles_pg',
       'Teammate_sack_fumbles_lost_pg', 'Teammate_passing_air_yards_pg',
       'Teammate_passing_yards_after_catch_pg',
       'Teammate_passing_first_downs_pg',
       'Teammate_passing_2pt_conversions_pg', 'Teammate_passing_10_pg',
       'Teammate_passing_16_pg', 'Teammate_passing_20_pg',
       'Teammate_passing_40_pg', 'Teammate_passing_epa_pg',
       'Teammate_passing_cpoe_pg', 'Teammate_fantasy_points_pg',
]

In [107]:
teammate_seasonal = teammate_seasonal.drop(passing_cols, axis=1)

In [108]:
teammate_seasonal[teammate_seasonal['Teammate_player_display_name'] == 'Jalen Coker']

,Teammate_player_display_name,Teammate_season,Teammate_carries_pg,Teammate_rushing_yards_pg,Teammate_rushing_tds_pg,Teammate_rushing_fumbles_pg,Teammate_rushing_fumbles_lost_pg,Teammate_rushing_first_downs_pg,Teammate_rushing_2pt_conversions_pg,Teammate_rushing_10_pg,Teammate_rushing_12_pg,Teammate_rushing_20_pg,Teammate_rushing_40_pg,Teammate_rushing_epa_pg,Teammate_receptions_pg,Teammate_targets_pg,Teammate_receiving_yards_pg,Teammate_receiving_tds_pg,Teammate_receiving_fumbles_pg,Teammate_receiving_fumbles_lost_pg,Teammate_receiving_air_yards_pg,Teammate_receiving_yards_after_catch_pg,Teammate_receiving_first_downs_pg,Teammate_receiving_2pt_conversions_pg,Teammate_receiving_10_pg,Teammate_receiving_16_pg,Teammate_receiving_20_pg,Teammate_receiving_40_pg,Teammate_air_yards_share_pg,Teammate_wopr_pg,Teammate_special_teams_tds_pg,Teammate_punt_returns_pg,Teammate_punt_return_yards_pg,Teammate_kickoff_returns_pg,Teammate_kickoff_return_yards_pg,Teammate_fantasy_points_ppr_pg,Teammate_games_played
5185,Jalen Coker,2024,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2.909091,4.181818,43.454545,0.181818,0.000000,0.000000,46.909091,15.545455,2.090909,0.000000,1.636364,0.818182,0.545455,0.090909,0.201400,0.362436,0.0,0.0,0.0,0.0,0.0,8.414545,11
5186,Jalen Coker,2025,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,3.000000,3.909091,35.818182,0.272727,0.090909,0.090909,39.545455,9.272727,2.000000,0.090909,1.454545,0.818182,0.545455,0.000000,0.199885,0.370905,0.0,0.0,0.0,0.0,0.0,8.218182,11

In [58]:
teammate_seasonal.columns

Index(['Teammate_player_display_name', 'Teammate_season',
       'Teammate_carries_pg', 'Teammate_rushing_yards_pg',
       'Teammate_rushing_tds_pg', 'Teammate_rushing_fumbles_pg',
       'Teammate_rushing_fumbles_lost_pg', 'Teammate_rushing_first_downs_pg',
       'Teammate_rushing_2pt_conversions_pg', 'Teammate_rushing_10_pg',
       'Teammate_rushing_12_pg', 'Teammate_rushing_20_pg',
       'Teammate_rushing_40_pg', 'Teammate_rushing_epa_pg',
       'Teammate_receptions_pg', 'Teammate_targets_pg',
       'Teammate_receiving_yards_pg', 'Teammate_receiving_tds_pg',
       'Teammate_receiving_fumbles_pg', 'Teammate_receiving_fumbles_lost_pg',
       'Teammate_receiving_air_yards_pg',
       'Teammate_receiving_yards_after_catch_pg',
       'Teammate_receiving_first_downs_pg',
       'Teammate_receiving_2pt_conversions_pg', 'Teammate_receiving_10_pg',
       'Teammate_receiving_16_pg', 'Teammate_receiving_20_pg',
       'Teammate_receiving_40_pg', 'Teammate_air_yards_share_pg',
       'Teammate_wopr_pg', 'Teammate_special_teams_tds_pg',
       'Teammate_punt_returns_pg', 'Teammate_punt_return_yards_pg',
       'Teammate_kickoff_returns_pg', 'Teammate_kickoff_return_yards_pg',
       'Teammate_fantasy_points_ppr_pg', 'Teammate_games_played'],
      dtype='str')

In [41]:
teammate_seasonal.to_csv("../outputs/teammate_season_stats_2020_2025.csv", index=False)

In [42]:
teammate_seasonal = pd.read_csv('../outputs/teammate_season_stats_2020_2025.csv')

**Quarterback Dataset**

I am now creating one more duplicate of these statistical dataframes because a part of my model will include the stats from the player's quarterback. Because of that I will be pulling from the rushing and receiving dataframes twice: once for the rookie's stats and once for the teammate's stats.

In [109]:
qb_seasonal = seasonal.copy()

In [110]:
qb_seasonal.columns = 'QB_' + qb_seasonal.columns

In [111]:
non_passing_cols = ['QB_carries_pg', 'QB_rushing_yards_pg',
       'QB_rushing_tds_pg', 'QB_rushing_fumbles_pg',
       'QB_rushing_fumbles_lost_pg', 'QB_rushing_first_downs_pg',
       'QB_rushing_2pt_conversions_pg', 'QB_rushing_10_pg', 'QB_rushing_12_pg',
       'QB_rushing_20_pg', 'QB_rushing_40_pg', 'QB_rushing_epa_pg',
       'QB_receptions_pg', 'QB_targets_pg', 'QB_receiving_yards_pg',
       'QB_receiving_tds_pg', 'QB_receiving_fumbles_pg',
       'QB_receiving_fumbles_lost_pg', 'QB_receiving_air_yards_pg',
       'QB_receiving_yards_after_catch_pg', 'QB_receiving_first_downs_pg',
       'QB_receiving_2pt_conversions_pg', 'QB_receiving_10_pg',
       'QB_receiving_16_pg', 'QB_receiving_20_pg', 'QB_receiving_40_pg',
       'QB_air_yards_share_pg', 'QB_wopr_pg', 'QB_special_teams_tds_pg',
       'QB_punt_returns_pg', 'QB_punt_return_yards_pg',
       'QB_kickoff_returns_pg', 'QB_kickoff_return_yards_pg',
       'QB_fantasy_points_pg',
]

In [112]:
qb_seasonal = qb_seasonal.drop(non_passing_cols, axis=1)

In [25]:
qb_seasonal[qb_seasonal['QB_player_display_name'] == 'Tyrod Taylor']

,QB_player_display_name,QB_season,QB_completions_pg,QB_attempts_pg,QB_passing_yards_pg,QB_passing_tds_pg,QB_passing_interceptions_pg,QB_sacks_suffered_pg,QB_sack_yards_lost_pg,QB_sack_fumbles_pg,QB_sack_fumbles_lost_pg,QB_passing_air_yards_pg,QB_passing_yards_after_catch_pg,QB_passing_first_downs_pg,QB_passing_2pt_conversions_pg,QB_passing_10_pg,QB_passing_16_pg,QB_passing_20_pg,QB_passing_40_pg,QB_passing_epa_pg,QB_passing_cpoe_pg,QB_fantasy_points_ppr_pg,QB_games_played
11513,Tyrod Taylor,2020,8.000000,15.000000,104.000000,0.000000,0.000000,1.000000,-0.500000,0.000000,0.000000,167.500000,40.000000,5.000000,0.0,4.500000,2.000000,1.500000,0.000000,-0.191233,-2.468618,4.510000,2
11514,Tyrod Taylor,2021,15.166667,25.000000,161.000000,0.833333,0.833333,2.166667,-19.833333,0.000000,0.000000,184.500000,81.833333,7.333333,0.0,6.166667,2.333333,2.166667,0.500000,-2.479269,-4.032346,13.623333,6
11515,Tyrod Taylor,2022,3.000000,4.000000,29.000000,0.500000,0.500000,1.500000,-9.000000,0.500000,0.500000,49.500000,13.000000,1.500000,0.5,1.500000,0.500000,0.000000,0.000000,-1.666168,2.872760,5.660000,2
11516,Tyrod Taylor,2023,11.600000,18.000000,134.100000,0.500000,0.300000,1.700000,-9.400000,0.200000,0.000000,154.100000,57.800000,5.200000,0.0,4.500000,2.900000,1.900000,0.400000,0.116902,-0.614916,8.734000,10
11517,Tyrod Taylor,2024,8.500000,11.000000,59.500000,1.500000,0.000000,0.000000,0.000000,0.000000,0.000000,44.000000,34.000000,4.500000,0.5,1.500000,0.500000,0.500000,0.000000,5.531543,12.303555,10.030000,2
11518,Tyrod Taylor,2025,13.333333,22.333333,129.833333,0.833333,0.833333,2.333333,-13.666667,0.166667,0.166667,190.833333,55.166667,6.833333,0.0,5.000000,1.500000,1.000000,0.333333,-2.219152,-7.356643,9.910000,6

In [57]:
qb_seasonal.columns

Index(['QB_player_display_name', 'QB_season', 'QB_completions_pg',
       'QB_attempts_pg', 'QB_passing_yards_pg', 'QB_passing_tds_pg',
       'QB_passing_interceptions_pg', 'QB_sacks_suffered_pg',
       'QB_sack_yards_lost_pg', 'QB_sack_fumbles_pg',
       'QB_sack_fumbles_lost_pg', 'QB_passing_air_yards_pg',
       'QB_passing_yards_after_catch_pg', 'QB_passing_first_downs_pg',
       'QB_passing_2pt_conversions_pg', 'QB_passing_10_pg', 'QB_passing_16_pg',
       'QB_passing_20_pg', 'QB_passing_40_pg', 'QB_passing_epa_pg',
       'QB_passing_cpoe_pg', 'QB_fantasy_points_ppr_pg', 'QB_games_played'],
      dtype='str')

In [32]:
qb_seasonal.to_csv("../outputs/qb_season_stats_2020_2025.csv", index=False)

In [33]:
qb_seasonal = pd.read_csv('../outputs/qb_season_stats_2020_2025.csv')

### Player Dataset

the previous season data for the player himself

In [113]:
player_previous_seasonal = seasonal.copy()

In [114]:
player_previous_seasonal.columns = 'Previous_' + player_previous_seasonal.columns

In [115]:
passing_cols = ['Previous_completions_pg', 'Previous_attempts_pg',
       'Previous_passing_yards_pg', 'Previous_passing_tds_pg',
       'Previous_passing_interceptions_pg', 'Previous_sacks_suffered_pg',
       'Previous_sack_yards_lost_pg', 'Previous_sack_fumbles_pg',
       'Previous_sack_fumbles_lost_pg', 'Previous_passing_air_yards_pg',
       'Previous_passing_yards_after_catch_pg',
       'Previous_passing_first_downs_pg',
       'Previous_passing_2pt_conversions_pg', 'Previous_passing_10_pg',
       'Previous_passing_16_pg', 'Previous_passing_20_pg',
       'Previous_passing_40_pg', 'Previous_passing_epa_pg',
       'Previous_passing_cpoe_pg',  'Previous_fantasy_points_pg',
]

In [116]:
player_previous_seasonal = player_previous_seasonal.drop(passing_cols, axis=1)

In [30]:
player_previous_seasonal[player_previous_seasonal['Previous_player_display_name'] == 'Odell Beckham']

,Previous_player_display_name,Previous_season,Previous_carries_pg,Previous_rushing_yards_pg,Previous_rushing_tds_pg,Previous_rushing_fumbles_pg,Previous_rushing_fumbles_lost_pg,Previous_rushing_first_downs_pg,Previous_rushing_2pt_conversions_pg,Previous_rushing_10_pg,Previous_rushing_12_pg,Previous_rushing_20_pg,Previous_rushing_40_pg,Previous_rushing_epa_pg,Previous_receptions_pg,Previous_targets_pg,Previous_receiving_yards_pg,Previous_receiving_tds_pg,Previous_receiving_fumbles_pg,Previous_receiving_fumbles_lost_pg,Previous_receiving_air_yards_pg,Previous_receiving_yards_after_catch_pg,Previous_receiving_first_downs_pg,Previous_receiving_2pt_conversions_pg,Previous_receiving_10_pg,Previous_receiving_16_pg,Previous_receiving_20_pg,Previous_receiving_40_pg,Previous_air_yards_share_pg,Previous_wopr_pg,Previous_special_teams_tds_pg,Previous_punt_returns_pg,Previous_punt_return_yards_pg,Previous_kickoff_returns_pg,Previous_kickoff_return_yards_pg,Previous_fantasy_points_ppr_pg,Previous_games_played
9085,Odell Beckham,2020,0.428571,10.285714,0.142857,0.0,0.0,0.285714,0.0,0.285714,0.285714,0.285714,0.142857,2.527460,3.285714,6.142857,45.571429,0.428571,0.000000,0.000000,83.428571,6.571429,2.428571,0.0,2.142857,1.000000,0.428571,0.142857,0.333189,0.563187,0.0,0.0,0.0,0.0,0.0,12.402857,7
9086,Odell Beckham,2021,0.142857,1.000000,0.000000,0.0,0.0,0.071429,0.0,0.071429,0.000000,0.000000,0.000000,0.232988,3.142857,5.857143,38.357143,0.357143,0.000000,0.000000,78.000000,10.785714,1.928571,0.0,1.357143,1.000000,0.500000,0.142857,0.260737,0.449264,0.0,0.0,0.0,0.0,0.0,9.221429,14
9087,Odell Beckham,2023,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,NaN,2.500000,4.571429,40.357143,0.214286,0.071429,0.071429,63.428571,11.071429,1.928571,0.0,1.571429,0.785714,0.714286,0.214286,0.243101,0.406095,0.0,0.0,0.0,0.0,0.0,7.678571,14
9088,Odell Beckham,2024,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,NaN,1.125000,2.250000,6.875000,0.000000,0.000000,0.000000,17.000000,1.750000,0.375000,0.0,0.125000,0.000000,0.000000,0.000000,0.080263,0.161314,0.0,0.0,0.0,0.0,0.0,1.812500,8

In [56]:
player_previous_seasonal.columns

Index(['Previous_player_display_name', 'Previous_season',
       'Previous_carries_pg', 'Previous_rushing_yards_pg',
       'Previous_rushing_tds_pg', 'Previous_rushing_fumbles_pg',
       'Previous_rushing_fumbles_lost_pg', 'Previous_rushing_first_downs_pg',
       'Previous_rushing_2pt_conversions_pg', 'Previous_rushing_10_pg',
       'Previous_rushing_12_pg', 'Previous_rushing_20_pg',
       'Previous_rushing_40_pg', 'Previous_rushing_epa_pg',
       'Previous_receptions_pg', 'Previous_targets_pg',
       'Previous_receiving_yards_pg', 'Previous_receiving_tds_pg',
       'Previous_receiving_fumbles_pg', 'Previous_receiving_fumbles_lost_pg',
       'Previous_receiving_air_yards_pg',
       'Previous_receiving_yards_after_catch_pg',
       'Previous_receiving_first_downs_pg',
       'Previous_receiving_2pt_conversions_pg', 'Previous_receiving_10_pg',
       'Previous_receiving_16_pg', 'Previous_receiving_20_pg',
       'Previous_receiving_40_pg', 'Previous_air_yards_share_pg',
       'Previous_wopr_pg', 'Previous_special_teams_tds_pg',
       'Previous_punt_returns_pg', 'Previous_punt_return_yards_pg',
       'Previous_kickoff_returns_pg', 'Previous_kickoff_return_yards_pg',
       'Previous_fantasy_points_ppr_pg', 'Previous_games_played'],
      dtype='str')

In [54]:
player_previous_seasonal.to_csv("../outputs/player_season_stats_2020_2025.csv", index=False)

In [55]:
player_previous_seasonal = pd.read_csv('../outputs/player_season_stats_2020_2025.csv')

### Target Dataset

In [60]:
seasonal.columns

Index(['player_display_name', 'season', 'completions_pg', 'attempts_pg',
       'passing_yards_pg', 'passing_tds_pg', 'passing_interceptions_pg',
       'sacks_suffered_pg', 'sack_yards_lost_pg', 'sack_fumbles_pg',
       'sack_fumbles_lost_pg', 'passing_air_yards_pg',
       'passing_yards_after_catch_pg', 'passing_first_downs_pg',
       'passing_2pt_conversions_pg', 'passing_10_pg', 'passing_16_pg',
       'passing_20_pg', 'passing_40_pg', 'passing_epa_pg', 'passing_cpoe_pg',
       'carries_pg', 'rushing_yards_pg', 'rushing_tds_pg',
       'rushing_fumbles_pg', 'rushing_fumbles_lost_pg',
       'rushing_first_downs_pg', 'rushing_2pt_conversions_pg', 'rushing_10_pg',
       'rushing_12_pg', 'rushing_20_pg', 'rushing_40_pg', 'rushing_epa_pg',
       'receptions_pg', 'targets_pg', 'receiving_yards_pg', 'receiving_tds_pg',
       'receiving_fumbles_pg', 'receiving_fumbles_lost_pg',
       'receiving_air_yards_pg', 'receiving_yards_after_catch_pg',
       'receiving_first_downs_pg', 'receiving_2pt_conversions_pg',
       'receiving_10_pg', 'receiving_16_pg', 'receiving_20_pg',
       'receiving_40_pg', 'air_yards_share_pg', 'wopr_pg',
       'special_teams_tds_pg', 'punt_returns_pg', 'punt_return_yards_pg',
       'kickoff_returns_pg', 'kickoff_return_yards_pg', 'fantasy_points_pg',
       'fantasy_points_ppr_pg', 'games_played'],
      dtype='str')

In [117]:
target = seasonal.copy()

In [118]:
non_target_cols = ['completions_pg', 'attempts_pg',
       'passing_yards_pg', 'passing_tds_pg', 'passing_interceptions_pg',
       'sacks_suffered_pg', 'sack_yards_lost_pg', 'sack_fumbles_pg',
       'sack_fumbles_lost_pg', 'passing_air_yards_pg',
       'passing_yards_after_catch_pg', 'passing_first_downs_pg',
       'passing_2pt_conversions_pg', 'passing_10_pg', 'passing_16_pg',
       'passing_20_pg', 'passing_40_pg', 'passing_epa_pg', 'passing_cpoe_pg',
       'carries_pg', 'rushing_yards_pg', 'rushing_tds_pg',
       'rushing_fumbles_pg', 'rushing_fumbles_lost_pg',
       'rushing_first_downs_pg', 'rushing_2pt_conversions_pg', 'rushing_10_pg',
       'rushing_12_pg', 'rushing_20_pg', 'rushing_40_pg', 'rushing_epa_pg',
       'receptions_pg', 'targets_pg', 'receiving_yards_pg', 'receiving_tds_pg',
       'receiving_fumbles_pg', 'receiving_fumbles_lost_pg',
       'receiving_air_yards_pg', 'receiving_yards_after_catch_pg',
       'receiving_first_downs_pg', 'receiving_2pt_conversions_pg',
       'receiving_10_pg', 'receiving_16_pg', 'receiving_20_pg',
       'receiving_40_pg', 'air_yards_share_pg', 'wopr_pg',
       'special_teams_tds_pg', 'punt_returns_pg', 'punt_return_yards_pg',
       'kickoff_returns_pg', 'kickoff_return_yards_pg', 'fantasy_points_pg', 'games_played'
]

In [119]:
target = target.drop(non_target_cols, axis=1)

In [34]:
target[target['player_display_name'] == 'Will Fuller']

      player_display_name  season  fantasy_points_ppr_pg
11684         Will Fuller    2020              17.172727
11685         Will Fuller    2021               4.300000

In [65]:
target.columns

Index(['player_display_name', 'season', 'fantasy_points_ppr_pg'], dtype='str')

In [66]:
target.to_csv("../outputs/player_fppg_stats_2020_2025.csv", index=False)

In [67]:
target = pd.read_csv('../outputs/player_fppg_stats_2020_2025.csv')

### Manual Input Dataset - WR

This dataset was put together from Claude and QA'd. It has the top 60 non-rookie WRs from 2021-2026, as well as that player's preseason projected QB and projected best WR teammate as well as their ages.

In [117]:
fantasy_board = pd.read_csv('../inputs/top60_preseason_wr_ppr_2021_2026.csv')

In [118]:
fantasy_board.head()

,preseason_rank,player_name,season,past_season,player_age,team,team_qb,team_qb_season,team_qb_age,teammate,teammate_season,teammate_age
0,1,Davante Adams,2021,2020,28,GB,Aaron Rodgers,2020,37,Allen Lazard,2020,26
1,2,Tyreek Hill,2021,2020,27,KC,Patrick Mahomes,2020,25,Mecole Hardman,2020,23
2,3,Stefon Diggs,2021,2020,27,BUF,Josh Allen,2020,25,Gabe Davis,2020,22
3,4,DeAndre Hopkins,2021,2020,29,ARI,Kyler Murray,2020,24,A.J. Green,2020,33
4,5,Calvin Ridley,2021,2020,26,ATL,Matt Ryan,2020,36,Russell Gage,2020,25

In [119]:
fantasy_board['player_name'] = (
    fantasy_board['player_name']
    .str.replace(r'\s+(Jr\.?|Sr\.?|II|III|IV|V)$', '', regex=True)
)

fantasy_board['team_qb'] = (
    fantasy_board['team_qb']
    .str.replace(r'\s+(Jr\.?|Sr\.?|II|III|IV|V)$', '', regex=True)
)

fantasy_board['teammate'] = (
    fantasy_board['teammate']
    .str.replace(r'\s+(Jr\.?|Sr\.?|II|III|IV|V)$', '', regex=True)
)

In [120]:
temp_wr_1 = pd.merge(fantasy_board, target, left_on=['player_name', 'season'], 
                   right_on=['player_display_name', 'season'], how='left')

In [121]:
temp_wr_2 = pd.merge(temp_wr_1, player_previous_seasonal, left_on=['player_name', 'past_season'], 
                   right_on=['Previous_player_display_name', 'Previous_season'], how='left')

In [122]:
temp_wr_3 = pd.merge(temp_wr_2, qb_seasonal, left_on=['team_qb', 'team_qb_season'], 
                   right_on=['QB_player_display_name', 'QB_season'], how='left')

In [123]:
final_wr = pd.merge(temp_wr_3, teammate_seasonal, left_on=['teammate', 'teammate_season'], 
                   right_on=['Teammate_player_display_name', 'Teammate_season'], how='left')

In [124]:
final_wr.head()

,preseason_rank,player_name,season,past_season,player_age,team,team_qb,team_qb_season,team_qb_age,teammate,teammate_season,teammate_age,player_display_name,fantasy_points_ppr_pg,Previous_player_display_name,Previous_season,Previous_carries_pg,Previous_rushing_yards_pg,Previous_rushing_tds_pg,Previous_rushing_fumbles_pg,Previous_rushing_fumbles_lost_pg,Previous_rushing_first_downs_pg,Previous_rushing_2pt_conversions_pg,Previous_rushing_10_pg,Previous_rushing_12_pg,Previous_rushing_20_pg,Previous_rushing_40_pg,Previous_rushing_epa_pg,Previous_receptions_pg,Previous_targets_pg,Previous_receiving_yards_pg,Previous_receiving_tds_pg,Previous_receiving_fumbles_pg,Previous_receiving_fumbles_lost_pg,Previous_receiving_air_yards_pg,Previous_receiving_yards_after_catch_pg,Previous_receiving_first_downs_pg,Previous_receiving_2pt_conversions_pg,Previous_receiving_10_pg,Previous_receiving_16_pg,Previous_receiving_20_pg,Previous_receiving_40_pg,Previous_air_yards_share_pg,Previous_wopr_pg,Previous_special_teams_tds_pg,Previous_punt_returns_pg,Previous_punt_return_yards_pg,Previous_kickoff_returns_pg,Previous_kickoff_return_yards_pg,Previous_fantasy_points_ppr_pg,Previous_games_played,QB_player_display_name,QB_season,QB_completions_pg,QB_attempts_pg,QB_passing_yards_pg,QB_passing_tds_pg,QB_passing_interceptions_pg,QB_sacks_suffered_pg,QB_sack_yards_lost_pg,QB_sack_fumbles_pg,QB_sack_fumbles_lost_pg,QB_passing_air_yards_pg,QB_passing_yards_after_catch_pg,QB_passing_first_downs_pg,QB_passing_2pt_conversions_pg,QB_passing_10_pg,QB_passing_16_pg,QB_passing_20_pg,QB_passing_40_pg,QB_passing_epa_pg,QB_passing_cpoe_pg,QB_fantasy_points_ppr_pg,QB_games_played,Teammate_player_display_name,Teammate_season,Teammate_carries_pg,Teammate_rushing_yards_pg,Teammate_rushing_tds_pg,Teammate_rushing_fumbles_pg,Teammate_rushing_fumbles_lost_pg,Teammate_rushing_first_downs_pg,Teammate_rushing_2pt_conversions_pg,Teammate_rushing_10_pg,Teammate_rushing_12_pg,Teammate_rushing_20_pg,Teammate_rushing_40_pg,Teammate_rushing_epa_pg,Teammate_receptions_pg,Teammate_targets_pg,Teammate_receiving_yards_pg,Teammate_receiving_tds_pg,Teammate_receiving_fumbles_pg,Teammate_receiving_fumbles_lost_pg,Teammate_receiving_air_yards_pg,Teammate_receiving_yards_after_catch_pg,Teammate_receiving_first_downs_pg,Teammate_receiving_2pt_conversions_pg,Teammate_receiving_10_pg,Teammate_receiving_16_pg,Teammate_receiving_20_pg,Teammate_receiving_40_pg,Teammate_air_yards_share_pg,Teammate_wopr_pg,Teammate_special_teams_tds_pg,Teammate_punt_returns_pg,Teammate_punt_return_yards_pg,Teammate_kickoff_returns_pg,Teammate_kickoff_return_yards_pg,Teammate_fantasy_points_ppr_pg,Teammate_games_played
0,1,Davante Adams,2021,2020,28,GB,Aaron Rodgers,2020,37,Allen Lazard,2020,26,Davante Adams,21.518750,Davante Adams,2020.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,NaN,8.214286,10.642857,98.142857,1.285714,0.071429,0.071429,95.000000,42.642857,5.214286,0.000000,3.500000,1.785714,1.285714,0.357143,0.383416,0.778455,0.0,0.000000,0.0,0.0,0.0,25.600000,14.0,Aaron Rodgers,2020,23.2500,32.875,268.6875,3.000000,0.3125,1.250000,-11.3750,0.0625,0.062500,258.4375,140.5000,13.500000,0.0000,9.750000,4.8125,3.562500,0.875000,11.640741,7.353442,23.95375,16,Allen Lazard,2020,0.2000,1.7000,0.0,0.0,0.0,0.1000,0.0,0.1000,0.100,0.0000,0.0,0.197563,3.3000,4.6000,45.1000,0.3000,0.0000,0.0000,45.8000,19.5000,2.3000,0.0000,1.5000,0.6000,0.6000,0.2000,0.187132,0.364185,0.0000,0.0000,0.0,0.0000,0.0,9.78000,10
1,2,Tyreek Hill,2021,2020,27,KC,Patrick Mahomes,2020,25,Mecole Hardman,2020,23,Tyreek Hill,17.441176,Tyreek Hill,2020.0,0.866667,8.200000,0.133333,0.0,0.0,0.333333,0.0,0.266667,0.2,0.2,0.0,0.820106,5.800000,9.000000,85.066667,1.000000,0.000000,0.000000,115.933333,28.933333,3.800000,0.000000,3.266667,1.800000,1.333333,0.333333,0.347848,0.592705,0.0,0.066667,0.0,0.0,0.0,21.926667,15.0,Patrick Mahomes,2020,26.0000,39.200,316.0000,2.533333,0.4000,1.466667,-9.8000,0.2000,0.133333,327.8000,149.4000,15.866667,0.2000,13.133333,6.8000,4.466667,0.533333,12.401960,3.186998,24.96000,15,Mecole Hardman,2020,0.2500,1.9375,0.0,0.0,0.0,0.1250,0.0,0.1250,0.125,0.0625,0.0,0.177859,2.5625,3.8750,35.0000,0.2500,0.0625,0.0625,41.2500,17.8125,1.4375,0.0625,1.3125,0.7500,0.4375,0.0625,0.113178,0.225886,0.0625,1.5625,11.0,0.5625,11.5,8.13125,16
2,3,Stefon Diggs,2021,2020,27,BUF,Josh Allen,2020,25,Gabe Davis,2020,22,Stefon Diggs,16.794118,Stefon Diggs,2020.0,0.062500,0.062500,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,-0.730859,7.937500,10.375000,95.937500,0.500000,0.000000,0.000000,104.625000,29.000000,4.562500,0.000000,3.875000,2.000000,1.250000,0.312500,0.339106,0.686056,0.0,0.000000,0.0,0.0,0.0,20.537500,16.0,Josh Allen,2020,24.7500,35.750,284.0000,2.312500,0.6250,1.625000,-9.9375,0.3125,0.125000,303.5625,116.9375,14.250000,0.0000,11.625000,5.6250,3.875000,0.500000,10.556718,6.462031,24.75375,16,Gabe Davis,2020,0.0625,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0000,0.000,0.0000,0.0,-0.742758,2.1875,3.8750,37.4375,0.4375,0.0625,0.0000,59.0625,8.1875,1.6875,0.0000,1.5625,0.7500,0.6250,0.1875,0.199350,0.300358,0.0000,0.0000,0.0,0.0000,0.0,8.55625,16
3,4,DeAndre Hopkins,2021,2020,29,ARI,Kyler Murray,2020,24,A.J. Green,2020,33,DeAndre Hopkins,14.720000,DeAndre Hopkins,2020.0,0.062500,0.062500,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.993359,7.187500,10.000000,87.937500,0.375000,0.187500,0.125000,89.500000,32.437500,4.687500,0.000000,3.562500,1.625000,1.062500,0.375000,0.334915,0.677152,0.0,0.000000,0.0,0.0,0.0,17.987500,16.0,Kyler Murray,2020,23.4375,34.875,248.1875,1.625000,0.7500,1.687500,-11.0000,0.2500,0.250000,272.1875,108.9375,12.812500,0.0000,8.875000,4.0625,2.750000,0.875000,1.994362,1.849077,23.67125,16,A.J. Green,2020,0.0000,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0000,0.000,0.0000,0.0,NaN,2.9375,6.5000,32.6875,0.1250,0.0000,0.0000,89.1875,5.3750,2.1250,0.0000,1.8125,0.5625,0.1875,0.0000,0.294294,0.476254,0.0000,0.0000,0.0,0.0000,0.0,6.95625,16
4,5,Calvin Ridley,2021,2020,26,ATL,Matt Ryan,2020,36,Russell Gage,2020,25,Calvin Ridley,14.220000,Calvin Ridley,2020.0,0.333333,0.066667,0.000000,0.0,0.0,0.066667,0.0,0.000000,0.0,0.0,0.0,-0.555594,6.000000,9.533333,91.600000,0.600000,0.066667,0.066667,136.800000,18.333333,4.333333,0.066667,3.866667,2.466667,1.533333,0.200000,0.399974,0.656419,0.0,0.000000,0.0,0.0,0.0,18.766667,15.0,Matt Ryan,2020,25.4375,39.125,286.3125,1.625000,0.6875,2.562500,-16.0625,0.2500,0.125000,333.8750,102.6250,15.125000,0.0625,11.937500,6.3125,3.625000,0.500000,4.223118,1.105596,17.65250,16,Russell Gage,2020,0.1250,0.5625,0.0,0.0,0.0,0.0625,0.0,0.0625,0.000,0.0000,0.0,-0.095199,4.5000,6.8125,49.1250,0.2500,0.0000,0.0000,57.9375,17.5625,3.1250,0.0000,2.2500,1.0000,0.3750,0.0000,0.168940,0.386043,0.0000,0.0000,0.0,0.0000,0.0,11.31625,16

**Data Cleaning**

Find players that did not have joined data because of formatting issues in names (capitalization, apostrophes, etc.) and change the name in the manual csv file. 

Once done, players with player_display_name NaN mean that they did not record any stats that season. Impute a zero for fantasy_points_ppr_pg.

Same with teammate_player_display_name.

Then rerun the isnull code and impute zeroes for anything remaining (not including fantasy points per game for 2026 rookies).

In [125]:
# View all rows where player_display_name is null
null_players_target = final_wr[final_wr['player_display_name'].isna()]

null_players_target.head(10)

,preseason_rank,player_name,season,past_season,player_age,team,team_qb,team_qb_season,team_qb_age,teammate,teammate_season,teammate_age,player_display_name,fantasy_points_ppr_pg,Previous_player_display_name,Previous_season,Previous_carries_pg,Previous_rushing_yards_pg,Previous_rushing_tds_pg,Previous_rushing_fumbles_pg,Previous_rushing_fumbles_lost_pg,Previous_rushing_first_downs_pg,Previous_rushing_2pt_conversions_pg,Previous_rushing_10_pg,Previous_rushing_12_pg,Previous_rushing_20_pg,Previous_rushing_40_pg,Previous_rushing_epa_pg,Previous_receptions_pg,Previous_targets_pg,Previous_receiving_yards_pg,Previous_receiving_tds_pg,Previous_receiving_fumbles_pg,Previous_receiving_fumbles_lost_pg,Previous_receiving_air_yards_pg,Previous_receiving_yards_after_catch_pg,Previous_receiving_first_downs_pg,Previous_receiving_2pt_conversions_pg,Previous_receiving_10_pg,Previous_receiving_16_pg,Previous_receiving_20_pg,Previous_receiving_40_pg,Previous_air_yards_share_pg,Previous_wopr_pg,Previous_special_teams_tds_pg,Previous_punt_returns_pg,Previous_punt_return_yards_pg,Previous_kickoff_returns_pg,Previous_kickoff_return_yards_pg,Previous_fantasy_points_ppr_pg,Previous_games_played,QB_player_display_name,QB_season,QB_completions_pg,QB_attempts_pg,QB_passing_yards_pg,QB_passing_tds_pg,QB_passing_interceptions_pg,QB_sacks_suffered_pg,QB_sack_yards_lost_pg,QB_sack_fumbles_pg,QB_sack_fumbles_lost_pg,QB_passing_air_yards_pg,QB_passing_yards_after_catch_pg,QB_passing_first_downs_pg,QB_passing_2pt_conversions_pg,QB_passing_10_pg,QB_passing_16_pg,QB_passing_20_pg,QB_passing_40_pg,QB_passing_epa_pg,QB_passing_cpoe_pg,QB_fantasy_points_ppr_pg,QB_games_played,Teammate_player_display_name,Teammate_season,Teammate_carries_pg,Teammate_rushing_yards_pg,Teammate_rushing_tds_pg,Teammate_rushing_fumbles_pg,Teammate_rushing_fumbles_lost_pg,Teammate_rushing_first_downs_pg,Teammate_rushing_2pt_conversions_pg,Teammate_rushing_10_pg,Teammate_rushing_12_pg,Teammate_rushing_20_pg,Teammate_rushing_40_pg,Teammate_rushing_epa_pg,Teammate_receptions_pg,Teammate_targets_pg,Teammate_receiving_yards_pg,Teammate_receiving_tds_pg,Teammate_receiving_fumbles_pg,Teammate_receiving_fumbles_lost_pg,Teammate_receiving_air_yards_pg,Teammate_receiving_yards_after_catch_pg,Teammate_receiving_first_downs_pg,Teammate_receiving_2pt_conversions_pg,Teammate_receiving_10_pg,Teammate_receiving_16_pg,Teammate_receiving_20_pg,Teammate_receiving_40_pg,Teammate_air_yards_share_pg,Teammate_wopr_pg,Teammate_special_teams_tds_pg,Teammate_punt_returns_pg,Teammate_punt_return_yards_pg,Teammate_kickoff_returns_pg,Teammate_kickoff_return_yards_pg,Teammate_fantasy_points_ppr_pg,Teammate_games_played
263,48,Brandon Aiyuk,2025,2024,27,SF,Brock Purdy,2024,25,Ricky Pearsall,2024,24,NaN,NaN,Brandon Aiyuk,2024.0,0.000000,0.000000,0.0000,0.0,0.0,0.000000,0.0,0.000000,0.0000,0.0000,0.0000,NaN,3.571429,6.714286,53.428571,0.000000,0.000000,0.000000,79.428571,15.285714,2.714286,0.000000,2.428571,1.142857,0.714286,0.142857,0.267098,0.519892,0.0,0.000000,0.0,0.0,0.0,8.914286,7.0,Brock Purdy,2024,20.000000,30.333333,257.600000,1.333333,0.800000,2.066667,-10.400000,0.333333,0.200000,260.266667,109.600000,11.866667,0.000000,10.400000,5.066667,3.733333,0.733333,5.185512,1.877466,17.790667,15,Ricky Pearsall,2024,0.272727,4.090909,0.0,0.0,0.0,0.090909,0.0,0.090909,0.090909,0.090909,0.0,1.103091,2.818182,4.181818,36.363636,0.272727,0.000000,0.000000,48.000000,10.363636,1.727273,0.000000,1.363636,0.545455,0.454545,0.181818,0.183686,0.320898,0.000000,0.272727,3.727273,0.000000,0.000000,8.500000,11
268,53,Diontae Johnson,2025,2024,29,BAL,Lamar Jackson,2024,28,Zay Flowers,2024,25,NaN,NaN,Diontae Johnson,2024.0,0.181818,0.545455,0.0000,0.0,0.0,0.090909,0.0,0.000000,0.0000,0.0000,0.0000,2.038883,3.000000,6.090909,34.090909,0.272727,0.000000,0.000000,66.454545,8.272727,1.909091,0.000000,1.545455,0.909091,0.454545,0.000000,0.324116,0.511485,0.0,0.090909,0.0,0.0,0.0,8.100000,11.0,Lamar Jackson,2024,18.588235,27.882353,245.411765,2.411765,0.235294,1.352941,-8.764706,0.117647,0.058824,241.705882,122.588235,11.647059,0.000000,10.294118,5.352941,3.294118,0.823529,10.134036,5.884127,25.316471,17,Zay Flowers,2024,0.529412,3.294118,0.0,0.0,0.0,0.058824,0.0,0.058824,0.058824,0.000000,0.0,0.268278,4.352941,6.823529,62.294118,0.235294,0.000000,0.000000,71.000000,27.235294,2.823529,0.000000,2.647059,1.529412,1.117647,0.235294,0.264979,0.566858,0.000000,0.000000,0.000000,0.000000,0.000000,12.323529,17
273,1,Puka Nacua,2026,2025,25,LAR,Matthew Stafford,2025,38,Davante Adams,2025,33,NaN,NaN,Puka Nacua,2025.0,0.625000,6.562500,0.0625,0.0,0.0,0.312500,0.0,0.250000,0.1875,0.0625,0.0625,1.333008,8.062500,10.375000,107.187500,0.625000,0.062500,0.062500,97.875000,41.625000,5.000000,0.000000,4.375000,2.187500,1.687500,0.187500,0.336906,0.687739,0.0,0.000000,0.0,0.0,0.0,23.437500,16.0,Matthew Stafford,2025,22.823529,35.117647,276.882353,2.705882,0.470588,1.352941,-8.823529,0.117647,0.117647,319.294118,108.823529,13.882353,0.000000,10.823529,5.823529,4.235294,0.470588,8.850253,1.720936,20.610588,17,Davante Adams,2025,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,NaN,4.285714,8.142857,56.357143,1.000000,0.000000,0.000000,103.142857,8.357143,3.642857,0.000000,2.500000,1.500000,1.000000,0.071429,0.376376,0.640645,0.000000,0.000000,0.000000,0.000000,0.000000,15.921429,14
274,2,Ja'Marr Chase,2026,2025,26,CIN,Joe Burrow,2025,29,Tee Higgins,2025,27,NaN,NaN,Ja'Marr Chase,2025.0,0.187500,0.875000,0.0000,0.0,0.0,0.000000,0.0,0.000000,0.0000,0.0000,0.0000,0.040955,7.812500,11.562500,88.250000,0.500000,0.062500,0.062500,98.125000,40.000000,4.562500,0.000000,3.937500,1.625000,0.937500,0.125000,0.365829,0.737066,0.0,0.000000,0.0,0.0,0.0,19.600000,16.0,Joe Burrow,2025,21.625000,32.375000,226.125000,2.125000,0.625000,2.125000,-14.125000,0.000000,0.000000,233.500000,103.000000,12.500000,0.000000,9.625000,3.750000,2.750000,0.125000,4.575887,4.629599,16.807500,8,Tee Higgins,2025,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,NaN,3.933333,6.533333,56.400000,0.733333,0.000000,0.000000,87.600000,11.066667,2.733333,0.066667,2.266667,1.333333,0.933333,0.200000,0.329933,0.504925,0.000000,0.000000,0.000000,0.000000,0.000000,14.106667,15
275,3,Jaxon Smith-Njigba,2026,2025,24,SEA,Sam Darnold,2025,29,Rashid Shaheed,2025,27,NaN,NaN,Jaxon Smith-Njigba,2025.0,0.411765,2.117647,0.0000,0.0,0.0,0.117647,0.0,0.176471,0.0000,0.0000,0.0000,0.009332,7.000000,9.588235,105.470588,0.588235,0.176471,0.058824,107.823529,31.058824,4.647059,0.000000,4.470588,2.470588,1.588235,0.470588,0.504316,0.904578,0.0,0.000000,0.0,0.0,0.0,21.170588,17.0,Sam Darnold,2025,19.000000,28.058824,238.117647,1.470588,0.823529,1.588235,-10.941176,0.411765,0.294118,220.235294,104.588235,10.470588,0.117647,9.647059,5.058824,3.352941,0.705882,4.386910,6.216144,13.848235,17,Rashid Shaheed,2025,0.500000,3.833333,0.0,0.0,0.0,0.166667,0.0,0.166667,0.055556,0.055556,0.0,0.139276,3.277778,5.111111,38.166667,0.111111,0.055556,0.055556,58.500000,9.833333,1.611111,0.000000,1.500000,0.611111,0.333333,0.055556,0.224294,0.399595,0.111111,1.277778,18.833333,0.833333,24.833333,8.700000,18
276,4,Amon-Ra St. Brown,2026,2025,27,DET,Jared Goff,2025,31,Jameson Williams,2025,25,NaN,NaN,Amon-Ra St. Brown,2025.0,0.176471,0.529412,0.0000,0.0,0.0,0.058824,0.0,0.000000,0.0000,0.0000,0.0000,0.278495,6.882353,10.117647,82.411765,0.647059,0.058824,0.000000,81.764706,33.529412,4.176471,0.000000,3.294118,2.000000,1.117647,0.058824,0.386639,0.745607,0.0,0.000000,0.0,0.0,0.0,19.058824,17.0,Jared Goff,2025,23.117647,34.000000,268.470588,2.000000,0.470588,2.235294,-15.235294,0.176471,0.176471,218.529412,142.470588,13.117647,0.000000,10.882353,5.941176,3.882353,0.470588,6.262362,2.889624,17.474118,17,Jameson Williams,2025,0.352941,0.705882,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,-0.237619,3.823529,6.000000,65.705882,0.411765,0.000000,0.000000,75.823529,25.941176,2.882353,0.000000,2.647059,1.823529,1.352941,0.294118,0.319457,0.502919,0.000000,0.000000,0.000000,0.000000,0.000000,12.935294,17
277,5,Drake London,2026,2025,25,ATL,Michael Penix,2025,26,Darnell Mooney,2025,27,NaN,NaN,Drake London,2025.0,0.000000,0.000000,0.0000,0.0,0.0,0.000000,0.0,0.000000,0.0000,0.0000,0.0000,NaN,5.666667,9.333333,76.583333,0.583333,0.083333,0.083333,101.750000,19.083333,3.833333,0.083333,3.333333,1.583333,1.083333,0.250000,0.402420,0.727361,0.0,0.000000,0.0,0.0,0.0,16.825000,12.0,Michael Penix,2025,18.444444,30.666667,220.222222,1.000000,0.333333,1.444444,-11.222222,0.333333,0.222222,255.555556,98.666667,11.000000,0.111111,9.666667,4.666667,2.888889,0.555556,0.571099,-2.522254,13.364444,9,Darnell Mooney,2025,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,NaN,2.133333,4.800000,29.533333,0.066667,0.133333,0.000000,67.933333,4.866667,1.666667,0.000000,1.400000,0.800000,0.333333,0.066667,0.279785,0.439080,0.000000,0.000000,0.000000,0.000000,0.000000,5.486667,15
278,6,CeeDee Lamb,2026,2025,27,DAL,Dak Prescott,2025,33,George Pickens,2025,25,NaN,NaN,CeeDee Lamb,2025.0,0.076923,0.153846,0.0000,0.0,0.0,0.000000,0.0,0.000000,0.0000,0.0000,0.0000,-0.247851,5.769231,9.000000,82.846154,0.230769,0.000000,0.000000,107.923077,24.846154,3.307692,0.000000,3.230769,1.923077,1.230769,0.230769,0.334998,0.611045,0.0,0.000000,0.0,0.0,0.0,15.453846,13.0,Dak Prescott,2025,23.764706,35.294118,267.764706,1.764706,0.588235,1.823529,-12.235294,0.117647,0.058824,282.882353,119.000000,12.941176,0.176471,10.764706,5.294118,3.117647,0.705882,6.664496,1.792896,18.457647,17,George Pickens,2025,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,NaN,5.470588,8.058824,84.058824,0.529412,0.235294,0.000000,91.000000,28.176471,4.294118,0.058824,3.647059,2.000000,1.294118,0.235294,0.322092,0.563192,0.000000,0.000000,0.000000,0.000000,0.000000,17.170588,17
279,7,Justin Jefferson,2026,2025,27,MIN,Kyler Murray,2025,29,Jauan Jennings,2025,29,NaN,NaN,Justin Jefferson,2025.0,0.117647,0.411765,0.0000,0.0,0.0,0.000000,0.0,0.000000,0.0000,0.0000,0.0000,-0.028360,4.941176,8.294118,61.647059,0.117647,0.000000,0.000000,84.588235,26.529412,2.764706,0.000000,3.058824,1.470588,0.705882,0.117647,0.401469,0.741072,0.0,0.000000,0.0,0.0,0.0,11.852941,17.0,Kyler Murray,2025,22.000000,32.200000,192.400000,1.200000,0.600000,3.200000,-22.200000,0.000000,0.000000,188.200000,109.000000,10.000000,0.000000,7.800000,3.400000,1.400000,0.400000,1.144118,-0.084823,15.556000,5,Jauan Jennings,2025,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,NaN,3.666667,6.000000,42.866667,0.600000,0.066667,0.066667,60.333333,12.066667,2.400000,0.066667,2.000000,0.800000,0.600000,0.066667,0.255767,0.477885,0.000000,0.000000,0.000000,0.000000,0.000000,11.553333,15
280,8,A.J. Brown,2026,2025,29,NE,Drake Maye,2025,23,Romeo Doubs,2025,26,NaN,NaN,A.J. Brown,2025.0,0.000000,0.000000,0.0000,0.0,0.0,0.000000,0.0,0.000000,0.0000,0.0000,0.0000,NaN,5.200000,8.066667,66.866667,0.466667,0.000000,0.000000,95.000000,17.866667,3.133333,0.000000,2.666667,1.666667,0.933333,0.066667,0.355210,0.678490,0.0,0.000000,0.0,0.0,0.0,14.686667,15.0,Drake Maye,2025,20.823529,28.941176,258.470588,1.823529,0.470588,2.764706,-11.823529,0.352941,0.176471,264.294118,102.705882,11.941176,0.058824,10.470588,5.823529,3.941176,0.352941,9.715385,12.160739,20.703529,17,Romeo Doubs,2025,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,NaN,3.437500,5.312500,45.250000,0.375000,0.062500,0.000000,67.812500,10.187500,2.562500,0.062500,1.875000,1.125000,0.750000,0.125000,0.280438,0.479481,0.000000,0.937500,5.875000,0.000000,0.000000,10.337500,16

In [98]:
seasonal[seasonal['player_display_name'] == "DJ Moore"]

,player_display_name,season,completions_pg,attempts_pg,passing_yards_pg,passing_tds_pg,passing_interceptions_pg,sacks_suffered_pg,sack_yards_lost_pg,sack_fumbles_pg,sack_fumbles_lost_pg,passing_air_yards_pg,passing_yards_after_catch_pg,passing_first_downs_pg,passing_2pt_conversions_pg,passing_10_pg,passing_16_pg,passing_20_pg,passing_40_pg,passing_epa_pg,passing_cpoe_pg,carries_pg,rushing_yards_pg,rushing_tds_pg,rushing_fumbles_pg,rushing_fumbles_lost_pg,rushing_first_downs_pg,rushing_2pt_conversions_pg,rushing_10_pg,rushing_12_pg,rushing_20_pg,rushing_40_pg,rushing_epa_pg,receptions_pg,targets_pg,receiving_yards_pg,receiving_tds_pg,receiving_fumbles_pg,receiving_fumbles_lost_pg,receiving_air_yards_pg,receiving_yards_after_catch_pg,receiving_first_downs_pg,receiving_2pt_conversions_pg,receiving_10_pg,receiving_16_pg,receiving_20_pg,receiving_40_pg,air_yards_share_pg,wopr_pg,special_teams_tds_pg,punt_returns_pg,punt_return_yards_pg,kickoff_returns_pg,kickoff_return_yards_pg,fantasy_points_pg,fantasy_points_ppr_pg,games_played
2660,DJ Moore,2020,0.000000,0.066667,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.400000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,-0.408471,-74.807233,0.133333,1.466667,0.000000,0.0,0.0,0.066667,0.0,0.066667,0.066667,0.066667,0.0,0.484478,4.400000,7.866667,79.533333,0.266667,0.000000,0.000000,104.066667,25.466667,3.533333,0.000000,3.266667,1.933333,1.266667,0.400000,0.404024,0.651482,0.0,0.000000,0.000000,0.000000,0.000000,9.700000,14.100000,15
2661,DJ Moore,2021,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.470588,2.823529,0.000000,0.0,0.0,0.235294,0.0,0.176471,0.117647,0.000000,0.0,1.058244,5.470588,9.588235,68.058824,0.235294,0.058824,0.058824,102.000000,24.823529,3.529412,0.058824,3.058824,1.647059,0.941176,0.058824,0.408123,0.712635,0.0,0.058824,0.529412,0.058824,0.764706,8.500000,13.970588,17
2662,DJ Moore,2022,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.588235,3.117647,0.000000,0.0,0.0,0.176471,0.0,0.058824,0.000000,0.000000,0.0,0.229414,3.705882,6.941176,52.235294,0.411765,0.000000,0.000000,89.764706,10.941176,2.588235,0.000000,2.117647,1.352941,1.000000,0.235294,0.531769,0.804432,0.0,0.000000,0.000000,0.000000,0.000000,8.005882,11.711765,17
2663,DJ Moore,2023,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.235294,1.235294,0.058824,0.0,0.0,0.058824,0.0,0.058824,0.058824,0.000000,0.0,-0.806124,5.647059,8.000000,80.235294,0.470588,0.058824,0.058824,86.823529,31.705882,3.764706,0.000000,3.117647,1.882353,1.470588,0.117647,0.401385,0.723262,0.0,0.000000,0.000000,0.000000,0.000000,11.205882,16.852941,17
2664,DJ Moore,2024,0.000000,0.058824,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,1.941176,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,-0.447272,-29.839304,0.823529,4.411765,0.000000,0.0,0.0,0.176471,0.0,0.176471,0.117647,0.000000,0.0,0.137396,5.764706,8.235294,56.823529,0.352941,0.058824,0.058824,61.705882,34.588235,2.529412,0.058824,2.352941,1.176471,0.647059,0.058824,0.238476,0.573303,0.0,0.000000,0.000000,0.000000,0.000000,8.241176,14.005882,17
2665,DJ Moore,2025,0.058824,0.058824,0.117647,0.058824,0.0,0.0,0.0,0.0,0.0,0.117647,0.0,0.058824,0.0,0.0,0.0,0.0,0.0,3.868194,46.214199,0.882353,4.647059,0.058824,0.0,0.0,0.294118,0.0,0.176471,0.117647,0.000000,0.0,0.463648,2.941176,5.000000,40.117647,0.352941,0.000000,0.000000,58.117647,13.058824,1.882353,0.000000,1.823529,1.117647,0.705882,0.117647,0.198831,0.381192,0.0,0.000000,0.000000,0.000000,0.000000,7.187059,10.128235,17

In [126]:
# View all rows where player_display_name is null
null_players_teammate = final_wr[final_wr['Teammate_player_display_name'].isna()]

null_players_teammate

Empty DataFrame
Columns: [preseason_rank, player_name, season, past_season, player_age, team, team_qb, team_qb_season, team_qb_age, teammate, teammate_season, teammate_age, player_display_name, fantasy_points_ppr_pg, Previous_player_display_name, Previous_season, Previous_carries_pg, Previous_rushing_yards_pg, Previous_rushing_tds_pg, Previous_rushing_fumbles_pg, Previous_rushing_fumbles_lost_pg, Previous_rushing_first_downs_pg, Previous_rushing_2pt_conversions_pg, Previous_rushing_10_pg, Previous_rushing_12_pg, Previous_rushing_20_pg, Previous_rushing_40_pg, Previous_rushing_epa_pg, Previous_receptions_pg, Previous_targets_pg, Previous_receiving_yards_pg, Previous_receiving_tds_pg, Previous_receiving_fumbles_pg, Previous_receiving_fumbles_lost_pg, Previous_receiving_air_yards_pg, Previous_receiving_yards_after_catch_pg, Previous_receiving_first_downs_pg, Previous_receiving_2pt_conversions_pg, Previous_receiving_10_pg, Previous_receiving_16_pg, Previous_receiving_20_pg, Previous_receiving_40_pg, Previous_air_yards_share_pg, Previous_wopr_pg, Previous_special_teams_tds_pg, Previous_punt_returns_pg, Previous_punt_return_yards_pg, Previous_kickoff_returns_pg, Previous_kickoff_return_yards_pg, Previous_fantasy_points_ppr_pg, Previous_games_played, QB_player_display_name, QB_season, QB_completions_pg, QB_attempts_pg, QB_passing_yards_pg, QB_passing_tds_pg, QB_passing_interceptions_pg, QB_sacks_suffered_pg, QB_sack_yards_lost_pg, QB_sack_fumbles_pg, QB_sack_fumbles_lost_pg, QB_passing_air_yards_pg, QB_passing_yards_after_catch_pg, QB_passing_first_downs_pg, QB_passing_2pt_conversions_pg, QB_passing_10_pg, QB_passing_16_pg, QB_passing_20_pg, QB_passing_40_pg, QB_passing_epa_pg, QB_passing_cpoe_pg, QB_fantasy_points_ppr_pg, QB_games_played, Teammate_player_display_name, Teammate_season, Teammate_carries_pg, Teammate_rushing_yards_pg, Teammate_rushing_tds_pg, Teammate_rushing_fumbles_pg, Teammate_rushing_fumbles_lost_pg, Teammate_rushing_first_downs_pg, Teammate_rushing_2pt_conversions_pg, Teammate_rushing_10_pg, Teammate_rushing_12_pg, Teammate_rushing_20_pg, Teammate_rushing_40_pg, Teammate_rushing_epa_pg, Teammate_receptions_pg, Teammate_targets_pg, Teammate_receiving_yards_pg, Teammate_receiving_tds_pg, Teammate_receiving_fumbles_pg, Teammate_receiving_fumbles_lost_pg, Teammate_receiving_air_yards_pg, Teammate_receiving_yards_after_catch_pg, Teammate_receiving_first_downs_pg, Teammate_receiving_2pt_conversions_pg, Teammate_receiving_10_pg, Teammate_receiving_16_pg, ...]
Index: []

In [127]:
# View all rows where player_display_name is null
null_players_qb = final_wr[final_wr['QB_player_display_name'].isna()]

null_players_qb

Empty DataFrame
Columns: [preseason_rank, player_name, season, past_season, player_age, team, team_qb, team_qb_season, team_qb_age, teammate, teammate_season, teammate_age, player_display_name, fantasy_points_ppr_pg, Previous_player_display_name, Previous_season, Previous_carries_pg, Previous_rushing_yards_pg, Previous_rushing_tds_pg, Previous_rushing_fumbles_pg, Previous_rushing_fumbles_lost_pg, Previous_rushing_first_downs_pg, Previous_rushing_2pt_conversions_pg, Previous_rushing_10_pg, Previous_rushing_12_pg, Previous_rushing_20_pg, Previous_rushing_40_pg, Previous_rushing_epa_pg, Previous_receptions_pg, Previous_targets_pg, Previous_receiving_yards_pg, Previous_receiving_tds_pg, Previous_receiving_fumbles_pg, Previous_receiving_fumbles_lost_pg, Previous_receiving_air_yards_pg, Previous_receiving_yards_after_catch_pg, Previous_receiving_first_downs_pg, Previous_receiving_2pt_conversions_pg, Previous_receiving_10_pg, Previous_receiving_16_pg, Previous_receiving_20_pg, Previous_receiving_40_pg, Previous_air_yards_share_pg, Previous_wopr_pg, Previous_special_teams_tds_pg, Previous_punt_returns_pg, Previous_punt_return_yards_pg, Previous_kickoff_returns_pg, Previous_kickoff_return_yards_pg, Previous_fantasy_points_ppr_pg, Previous_games_played, QB_player_display_name, QB_season, QB_completions_pg, QB_attempts_pg, QB_passing_yards_pg, QB_passing_tds_pg, QB_passing_interceptions_pg, QB_sacks_suffered_pg, QB_sack_yards_lost_pg, QB_sack_fumbles_pg, QB_sack_fumbles_lost_pg, QB_passing_air_yards_pg, QB_passing_yards_after_catch_pg, QB_passing_first_downs_pg, QB_passing_2pt_conversions_pg, QB_passing_10_pg, QB_passing_16_pg, QB_passing_20_pg, QB_passing_40_pg, QB_passing_epa_pg, QB_passing_cpoe_pg, QB_fantasy_points_ppr_pg, QB_games_played, Teammate_player_display_name, Teammate_season, Teammate_carries_pg, Teammate_rushing_yards_pg, Teammate_rushing_tds_pg, Teammate_rushing_fumbles_pg, Teammate_rushing_fumbles_lost_pg, Teammate_rushing_first_downs_pg, Teammate_rushing_2pt_conversions_pg, Teammate_rushing_10_pg, Teammate_rushing_12_pg, Teammate_rushing_20_pg, Teammate_rushing_40_pg, Teammate_rushing_epa_pg, Teammate_receptions_pg, Teammate_targets_pg, Teammate_receiving_yards_pg, Teammate_receiving_tds_pg, Teammate_receiving_fumbles_pg, Teammate_receiving_fumbles_lost_pg, Teammate_receiving_air_yards_pg, Teammate_receiving_yards_after_catch_pg, Teammate_receiving_first_downs_pg, Teammate_receiving_2pt_conversions_pg, Teammate_receiving_10_pg, Teammate_receiving_16_pg, ...]
Index: []

In [116]:
seasonal[seasonal['player_display_name'] == "Ja'Marr Chase"]

,player_display_name,season,completions_pg,attempts_pg,passing_yards_pg,passing_tds_pg,passing_interceptions_pg,sacks_suffered_pg,sack_yards_lost_pg,sack_fumbles_pg,sack_fumbles_lost_pg,passing_air_yards_pg,passing_yards_after_catch_pg,passing_first_downs_pg,passing_2pt_conversions_pg,passing_10_pg,passing_16_pg,passing_20_pg,passing_40_pg,passing_epa_pg,passing_cpoe_pg,carries_pg,rushing_yards_pg,rushing_tds_pg,rushing_fumbles_pg,rushing_fumbles_lost_pg,rushing_first_downs_pg,rushing_2pt_conversions_pg,rushing_10_pg,rushing_12_pg,rushing_20_pg,rushing_40_pg,rushing_epa_pg,receptions_pg,targets_pg,receiving_yards_pg,receiving_tds_pg,receiving_fumbles_pg,receiving_fumbles_lost_pg,receiving_air_yards_pg,receiving_yards_after_catch_pg,receiving_first_downs_pg,receiving_2pt_conversions_pg,receiving_10_pg,receiving_16_pg,receiving_20_pg,receiving_40_pg,air_yards_share_pg,wopr_pg,special_teams_tds_pg,punt_returns_pg,punt_return_yards_pg,kickoff_returns_pg,kickoff_return_yards_pg,fantasy_points_pg,fantasy_points_ppr_pg,games_played
4884,Ja'Marr Chase,2021,0.0000,0.0000,0.0000,0.0,0.0,0.000000,0.00,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.411765,1.235294,0.0,0.0,0.0,0.117647,0.0,0.058824,0.000000,0.0,0.0,-0.445415,4.764706,7.529412,85.588235,0.764706,0.117647,0.058824,95.117647,38.294118,3.294118,0.0,3.000000,1.882353,1.294118,0.470588,0.364920,0.603939,0.0,0.0,0.0,0.0,0.0,13.152941,17.917647,17
4885,Ja'Marr Chase,2022,0.0000,0.0000,0.0000,0.0,0.0,0.083333,-0.75,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.604014,NaN,0.416667,0.666667,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,-1.505549,7.250000,11.166667,87.166667,0.750000,0.166667,0.166667,101.666667,35.083333,4.833333,0.0,3.750000,1.416667,1.083333,0.250000,0.386652,0.713566,0.0,0.0,0.0,0.0,0.0,12.950000,20.200000,12
4886,Ja'Marr Chase,2023,0.0625,0.0625,-0.4375,0.0,0.0,0.000000,0.00,0.0,0.0,-0.4375,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.102857,17.854065,0.187500,-0.375000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,-1.368989,6.250000,9.062500,76.000000,0.437500,0.062500,0.000000,78.375000,33.812500,3.937500,0.0,3.000000,1.375000,0.875000,0.250000,0.345560,0.632610,0.0,0.0,0.0,0.0,0.0,10.170000,16.420000,16
4887,Ja'Marr Chase,2024,0.0000,0.0000,0.0000,0.0,0.0,0.000000,0.00,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.176471,1.882353,0.0,0.0,0.0,0.117647,0.0,0.117647,0.058824,0.0,0.0,0.673911,7.470588,10.294118,100.470588,1.000000,0.000000,0.000000,89.764706,46.294118,4.411765,0.0,3.705882,1.882353,1.117647,0.470588,0.318476,0.631403,0.0,0.0,0.0,0.0,0.0,16.235294,23.705882,17
4888,Ja'Marr Chase,2025,0.0000,0.0000,0.0000,0.0,0.0,0.000000,0.00,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.187500,0.875000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.040955,7.812500,11.562500,88.250000,0.500000,0.062500,0.062500,98.125000,40.000000,4.562500,0.0,3.937500,1.625000,0.937500,0.125000,0.365829,0.737066,0.0,0.0,0.0,0.0,0.0,11.787500,19.600000,16

Names to fix: Josh Palmer, A.J. Green, A.J. Brown, K.J. Osborn, T.Y. Hilton, Robbie Chosen, C.J. Stroud, C.J. Beathard.

In [129]:
final_wr[final_wr["Previous_player_display_name"].isna()]

,preseason_rank,player_name,season,past_season,player_age,team,team_qb,team_qb_season,team_qb_age,teammate,teammate_season,teammate_age,player_display_name,fantasy_points_ppr_pg,Previous_player_display_name,Previous_season,Previous_carries_pg,Previous_rushing_yards_pg,Previous_rushing_tds_pg,Previous_rushing_fumbles_pg,Previous_rushing_fumbles_lost_pg,Previous_rushing_first_downs_pg,Previous_rushing_2pt_conversions_pg,Previous_rushing_10_pg,Previous_rushing_12_pg,Previous_rushing_20_pg,Previous_rushing_40_pg,Previous_rushing_epa_pg,Previous_receptions_pg,Previous_targets_pg,Previous_receiving_yards_pg,Previous_receiving_tds_pg,Previous_receiving_fumbles_pg,Previous_receiving_fumbles_lost_pg,Previous_receiving_air_yards_pg,Previous_receiving_yards_after_catch_pg,Previous_receiving_first_downs_pg,Previous_receiving_2pt_conversions_pg,Previous_receiving_10_pg,Previous_receiving_16_pg,Previous_receiving_20_pg,Previous_receiving_40_pg,Previous_air_yards_share_pg,Previous_wopr_pg,Previous_special_teams_tds_pg,Previous_punt_returns_pg,Previous_punt_return_yards_pg,Previous_kickoff_returns_pg,Previous_kickoff_return_yards_pg,Previous_fantasy_points_ppr_pg,Previous_games_played,QB_player_display_name,QB_season,QB_completions_pg,QB_attempts_pg,QB_passing_yards_pg,QB_passing_tds_pg,QB_passing_interceptions_pg,QB_sacks_suffered_pg,QB_sack_yards_lost_pg,QB_sack_fumbles_pg,QB_sack_fumbles_lost_pg,QB_passing_air_yards_pg,QB_passing_yards_after_catch_pg,QB_passing_first_downs_pg,QB_passing_2pt_conversions_pg,QB_passing_10_pg,QB_passing_16_pg,QB_passing_20_pg,QB_passing_40_pg,QB_passing_epa_pg,QB_passing_cpoe_pg,QB_fantasy_points_ppr_pg,QB_games_played,Teammate_player_display_name,Teammate_season,Teammate_carries_pg,Teammate_rushing_yards_pg,Teammate_rushing_tds_pg,Teammate_rushing_fumbles_pg,Teammate_rushing_fumbles_lost_pg,Teammate_rushing_first_downs_pg,Teammate_rushing_2pt_conversions_pg,Teammate_rushing_10_pg,Teammate_rushing_12_pg,Teammate_rushing_20_pg,Teammate_rushing_40_pg,Teammate_rushing_epa_pg,Teammate_receptions_pg,Teammate_targets_pg,Teammate_receiving_yards_pg,Teammate_receiving_tds_pg,Teammate_receiving_fumbles_pg,Teammate_receiving_fumbles_lost_pg,Teammate_receiving_air_yards_pg,Teammate_receiving_yards_after_catch_pg,Teammate_receiving_first_downs_pg,Teammate_receiving_2pt_conversions_pg,Teammate_receiving_10_pg,Teammate_receiving_16_pg,Teammate_receiving_20_pg,Teammate_receiving_40_pg,Teammate_air_yards_share_pg,Teammate_wopr_pg,Teammate_special_teams_tds_pg,Teammate_punt_returns_pg,Teammate_punt_return_yards_pg,Teammate_kickoff_returns_pg,Teammate_kickoff_return_yards_pg,Teammate_fantasy_points_ppr_pg,Teammate_games_played
29,30,Ja'Marr Chase,2021,2020,21,CIN,Joe Burrow,2020,24,Tee Higgins,2020,22,Ja'Marr Chase,17.917647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Joe Burrow,2020,26.400000,40.400000,268.800000,1.300000,0.500000,3.200000,-23.100000,0.400000,0.300000,342.900000,114.200000,15.000000,0.000000,12.000000,4.600000,2.300000,0.300000,4.896672,1.898641,17.372000,10,Tee Higgins,2020,0.333333,1.866667,0.0,0.0,0.0,0.066667,0.0,0.066667,0.066667,0.0,0.0,0.252925,4.466667,7.200000,60.533333,0.400000,0.066667,0.066667,82.733333,20.666667,3.466667,0.0,2.600000,1.400000,0.933333,0.133333,0.276502,0.520051,0.0,0.000000,0.000000,0.0,0.0,12.973333,15
38,39,Jaylen Waddle,2021,2020,20,MIA,Tua Tagovailoa,2020,23,DeVante Parker,2020,24,Jaylen Waddle,15.487500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tua Tagovailoa,2020,18.600000,29.000000,181.400000,1.100000,0.500000,2.000000,-13.600000,0.100000,0.100000,217.500000,76.600000,10.000000,0.100000,7.600000,3.400000,1.500000,0.000000,-1.435119,2.113032,13.546000,10,DeVante Parker,2020,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,NaN,4.500000,7.357143,56.642857,0.285714,0.071429,0.000000,72.142857,12.357143,3.214286,0.0,2.500000,1.642857,0.714286,0.000000,0.260203,0.498878,0.0,0.000000,0.000000,0.0,0.0,11.878571,14
122,15,Calvin Ridley,2023,2022,28,JAX,Trevor Lawrence,2022,23,Christian Kirk,2022,26,Calvin Ridley,13.523529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Trevor Lawrence,2022,22.764706,34.352941,241.941176,1.470588,0.470588,1.588235,-10.823529,0.411765,0.294118,252.588235,118.647059,12.117647,0.176471,9.882353,4.882353,3.235294,0.176471,4.931980,1.785433,17.389412,17,Christian Kirk,2022,0.294118,0.647059,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,-0.166240,4.941176,7.823529,65.176471,0.470588,0.058824,0.058824,71.529412,21.823529,3.176471,0.0,2.647059,1.470588,1.058824,0.117647,0.278837,0.549823,0.0,0.235294,1.470588,0.0,0.0,14.229412,17
157,50,Odell Beckham,2023,2022,30,BAL,Lamar Jackson,2022,26,Rashod Bateman,2022,24,Odell Beckham,7.678571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lamar Jackson,2022,13.533333,21.733333,149.466667,1.133333,0.466667,1.733333,-7.600000,0.066667,0.066667,183.600000,64.933333,7.000000,0.066667,6.266667,3.200000,1.600000,0.266667,0.873361,-1.451075,15.738667,15,Rashod Bateman,2022,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,NaN,2.500000,4.666667,47.500000,0.333333,0.166667,0.166667,62.333333,22.166667,1.166667,0.0,1.166667,1.000000,0.833333,0.333333,0.276340,0.472973,0.0,0.000000,0.000000,0.0,0.0,8.916667,6

In [130]:
final_wr = final_wr[final_wr["Previous_player_display_name"].notna()].copy()

The code above removes some rows where rookies were mistakenly pulled into the dataset. This is problematic because then there is no previous season data for the model.

In [133]:
final_wr[final_wr["player_display_name"].isna()]

,preseason_rank,player_name,season,past_season,player_age,team,team_qb,team_qb_season,team_qb_age,teammate,teammate_season,teammate_age,player_display_name,fantasy_points_ppr_pg,Previous_player_display_name,Previous_season,Previous_carries_pg,Previous_rushing_yards_pg,Previous_rushing_tds_pg,Previous_rushing_fumbles_pg,Previous_rushing_fumbles_lost_pg,Previous_rushing_first_downs_pg,Previous_rushing_2pt_conversions_pg,Previous_rushing_10_pg,Previous_rushing_12_pg,Previous_rushing_20_pg,Previous_rushing_40_pg,Previous_rushing_epa_pg,Previous_receptions_pg,Previous_targets_pg,Previous_receiving_yards_pg,Previous_receiving_tds_pg,Previous_receiving_fumbles_pg,Previous_receiving_fumbles_lost_pg,Previous_receiving_air_yards_pg,Previous_receiving_yards_after_catch_pg,Previous_receiving_first_downs_pg,Previous_receiving_2pt_conversions_pg,Previous_receiving_10_pg,Previous_receiving_16_pg,Previous_receiving_20_pg,Previous_receiving_40_pg,Previous_air_yards_share_pg,Previous_wopr_pg,Previous_special_teams_tds_pg,Previous_punt_returns_pg,Previous_punt_return_yards_pg,Previous_kickoff_returns_pg,Previous_kickoff_return_yards_pg,Previous_fantasy_points_ppr_pg,Previous_games_played,QB_player_display_name,QB_season,QB_completions_pg,QB_attempts_pg,QB_passing_yards_pg,QB_passing_tds_pg,QB_passing_interceptions_pg,QB_sacks_suffered_pg,QB_sack_yards_lost_pg,QB_sack_fumbles_pg,QB_sack_fumbles_lost_pg,QB_passing_air_yards_pg,QB_passing_yards_after_catch_pg,QB_passing_first_downs_pg,QB_passing_2pt_conversions_pg,QB_passing_10_pg,QB_passing_16_pg,QB_passing_20_pg,QB_passing_40_pg,QB_passing_epa_pg,QB_passing_cpoe_pg,QB_fantasy_points_ppr_pg,QB_games_played,Teammate_player_display_name,Teammate_season,Teammate_carries_pg,Teammate_rushing_yards_pg,Teammate_rushing_tds_pg,Teammate_rushing_fumbles_pg,Teammate_rushing_fumbles_lost_pg,Teammate_rushing_first_downs_pg,Teammate_rushing_2pt_conversions_pg,Teammate_rushing_10_pg,Teammate_rushing_12_pg,Teammate_rushing_20_pg,Teammate_rushing_40_pg,Teammate_rushing_epa_pg,Teammate_receptions_pg,Teammate_targets_pg,Teammate_receiving_yards_pg,Teammate_receiving_tds_pg,Teammate_receiving_fumbles_pg,Teammate_receiving_fumbles_lost_pg,Teammate_receiving_air_yards_pg,Teammate_receiving_yards_after_catch_pg,Teammate_receiving_first_downs_pg,Teammate_receiving_2pt_conversions_pg,Teammate_receiving_10_pg,Teammate_receiving_16_pg,Teammate_receiving_20_pg,Teammate_receiving_40_pg,Teammate_air_yards_share_pg,Teammate_wopr_pg,Teammate_special_teams_tds_pg,Teammate_punt_returns_pg,Teammate_punt_return_yards_pg,Teammate_kickoff_returns_pg,Teammate_kickoff_return_yards_pg,Teammate_fantasy_points_ppr_pg,Teammate_games_played
263,48,Brandon Aiyuk,2025,2024,27,SF,Brock Purdy,2024,25,Ricky Pearsall,2024,24,NaN,NaN,Brandon Aiyuk,2024.0,0.000000,0.000000,0.000000,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,NaN,3.571429,6.714286,53.428571,0.000000,0.000000,0.000000,79.428571,15.285714,2.714286,0.000000,2.428571,1.142857,0.714286,0.142857,0.267098,0.519892,0.000000,0.000000,0.000000,0.000000,0.000000,8.914286,7.0,Brock Purdy,2024,20.000000,30.333333,257.600000,1.333333,0.800000,2.066667,-10.400000,0.333333,0.200000,260.266667,109.600000,11.866667,0.000000,10.400000,5.066667,3.733333,0.733333,5.185512,1.877466,17.790667,15,Ricky Pearsall,2024,0.272727,4.090909,0.000000,0.000000,0.000000,0.090909,0.0,0.090909,0.090909,0.090909,0.0000,1.103091,2.818182,4.181818,36.363636,0.272727,0.000000,0.000000,48.000000,10.363636,1.727273,0.000000,1.363636,0.545455,0.454545,0.181818,0.183686,0.320898,0.000000,0.272727,3.727273,0.000000,0.000000,8.500000,11
268,53,Diontae Johnson,2025,2024,29,BAL,Lamar Jackson,2024,28,Zay Flowers,2024,25,NaN,NaN,Diontae Johnson,2024.0,0.181818,0.545455,0.000000,0.000,0.0,0.090909,0.0,0.000000,0.000000,0.000000,0.0000,2.038883,3.000000,6.090909,34.090909,0.272727,0.000000,0.000000,66.454545,8.272727,1.909091,0.000000,1.545455,0.909091,0.454545,0.000000,0.324116,0.511485,0.000000,0.090909,0.000000,0.000000,0.000000,8.100000,11.0,Lamar Jackson,2024,18.588235,27.882353,245.411765,2.411765,0.235294,1.352941,-8.764706,0.117647,0.058824,241.705882,122.588235,11.647059,0.000000,10.294118,5.352941,3.294118,0.823529,10.134036,5.884127,25.316471,17,Zay Flowers,2024,0.529412,3.294118,0.000000,0.000000,0.000000,0.058824,0.0,0.058824,0.058824,0.000000,0.0000,0.268278,4.352941,6.823529,62.294118,0.235294,0.000000,0.000000,71.000000,27.235294,2.823529,0.000000,2.647059,1.529412,1.117647,0.235294,0.264979,0.566858,0.000000,0.000000,0.000000,0.000000,0.000000,12.323529,17
273,1,Puka Nacua,2026,2025,25,LAR,Matthew Stafford,2025,38,Davante Adams,2025,33,NaN,NaN,Puka Nacua,2025.0,0.625000,6.562500,0.062500,0.000,0.0,0.312500,0.0,0.250000,0.187500,0.062500,0.0625,1.333008,8.062500,10.375000,107.187500,0.625000,0.062500,0.062500,97.875000,41.625000,5.000000,0.000000,4.375000,2.187500,1.687500,0.187500,0.336906,0.687739,0.000000,0.000000,0.000000,0.000000,0.000000,23.437500,16.0,Matthew Stafford,2025,22.823529,35.117647,276.882353,2.705882,0.470588,1.352941,-8.823529,0.117647,0.117647,319.294118,108.823529,13.882353,0.000000,10.823529,5.823529,4.235294,0.470588,8.850253,1.720936,20.610588,17,Davante Adams,2025,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,NaN,4.285714,8.142857,56.357143,1.000000,0.000000,0.000000,103.142857,8.357143,3.642857,0.000000,2.500000,1.500000,1.000000,0.071429,0.376376,0.640645,0.000000,0.000000,0.000000,0.000000,0.000000,15.921429,14
274,2,Ja'Marr Chase,2026,2025,26,CIN,Joe Burrow,2025,29,Tee Higgins,2025,27,NaN,NaN,Ja'Marr Chase,2025.0,0.187500,0.875000,0.000000,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,0.040955,7.812500,11.562500,88.250000,0.500000,0.062500,0.062500,98.125000,40.000000,4.562500,0.000000,3.937500,1.625000,0.937500,0.125000,0.365829,0.737066,0.000000,0.000000,0.000000,0.000000,0.000000,19.600000,16.0,Joe Burrow,2025,21.625000,32.375000,226.125000,2.125000,0.625000,2.125000,-14.125000,0.000000,0.000000,233.500000,103.000000,12.500000,0.000000,9.625000,3.750000,2.750000,0.125000,4.575887,4.629599,16.807500,8,Tee Higgins,2025,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,NaN,3.933333,6.533333,56.400000,0.733333,0.000000,0.000000,87.600000,11.066667,2.733333,0.066667,2.266667,1.333333,0.933333,0.200000,0.329933,0.504925,0.000000,0.000000,0.000000,0.000000,0.000000,14.106667,15
275,3,Jaxon Smith-Njigba,2026,2025,24,SEA,Sam Darnold,2025,29,Rashid Shaheed,2025,27,NaN,NaN,Jaxon Smith-Njigba,2025.0,0.411765,2.117647,0.000000,0.000,0.0,0.117647,0.0,0.176471,0.000000,0.000000,0.0000,0.009332,7.000000,9.588235,105.470588,0.588235,0.176471,0.058824,107.823529,31.058824,4.647059,0.000000,4.470588,2.470588,1.588235,0.470588,0.504316,0.904578,0.000000,0.000000,0.000000,0.000000,0.000000,21.170588,17.0,Sam Darnold,2025,19.000000,28.058824,238.117647,1.470588,0.823529,1.588235,-10.941176,0.411765,0.294118,220.235294,104.588235,10.470588,0.117647,9.647059,5.058824,3.352941,0.705882,4.386910,6.216144,13.848235,17,Rashid Shaheed,2025,0.500000,3.833333,0.000000,0.000000,0.000000,0.166667,0.0,0.166667,0.055556,0.055556,0.0000,0.139276,3.277778,5.111111,38.166667,0.111111,0.055556,0.055556,58.500000,9.833333,1.611111,0.000000,1.500000,0.611111,0.333333,0.055556,0.224294,0.399595,0.111111,1.277778,18.833333,0.833333,24.833333,8.700000,18
276,4,Amon-Ra St. Brown,2026,2025,27,DET,Jared Goff,2025,31,Jameson Williams,2025,25,NaN,NaN,Amon-Ra St. Brown,2025.0,0.176471,0.529412,0.000000,0.000,0.0,0.058824,0.0,0.000000,0.000000,0.000000,0.0000,0.278495,6.882353,10.117647,82.411765,0.647059,0.058824,0.000000,81.764706,33.529412,4.176471,0.000000,3.294118,2.000000,1.117647,0.058824,0.386639,0.745607,0.000000,0.000000,0.000000,0.000000,0.000000,19.058824,17.0,Jared Goff,2025,23.117647,34.000000,268.470588,2.000000,0.470588,2.235294,-15.235294,0.176471,0.176471,218.529412,142.470588,13.117647,0.000000,10.882353,5.941176,3.882353,0.470588,6.262362,2.889624,17.474118,17,Jameson Williams,2025,0.352941,0.705882,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,-0.237619,3.823529,6.000000,65.705882,0.411765,0.000000,0.000000,75.823529,25.941176,2.882353,0.000000,2.647059,1.823529,1.352941,0.294118,0.319457,0.502919,0.000000,0.000000,0.000000,0.000000,0.000000,12.935294,17
277,5,Drake London,2026,2025,25,ATL,Michael Penix,2025,26,Darnell Mooney,2025,27,NaN,NaN,Drake London,2025.0,0.000000,0.000000,0.000000,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,NaN,5.666667,9.333333,76.583333,0.583333,0.083333,0.083333,101.750000,19.083333,3.833333,0.083333,3.333333,1.583333,1.083333,0.250000,0.402420,0.727361,0.000000,0.000000,0.000000,0.000000,0.000000,16.825000,12.0,Michael Penix,2025,18.444444,30.666667,220.222222,1.000000,0.333333,1.444444,-11.222222,0.333333,0.222222,255.555556,98.666667,11.000000,0.111111,9.666667,4.666667,2.888889,0.555556,0.571099,-2.522254,13.364444,9,Darnell Mooney,2025,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,NaN,2.133333,4.800000,29.533333,0.066667,0.133333,0.000000,67.933333,4.866667,1.666667,0.000000,1.400000,0.800000,0.333333,0.066667,0.279785,0.439080,0.000000,0.000000,0.000000,0.000000,0.000000,5.486667,15
278,6,CeeDee Lamb,2026,2025,27,DAL,Dak Prescott,2025,33,George Pickens,2025,25,NaN,NaN,CeeDee Lamb,2025.0,0.076923,0.153846,0.000000,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,-0.247851,5.769231,9.000000,82.846154,0.230769,0.000000,0.000000,107.923077,24.846154,3.307692,0.000000,3.230769,1.923077,1.230769,0.230769,0.334998,0.611045,0.000000,0.000000,0.000000,0.000000,0.000000,15.453846,13.0,Dak Prescott,2025,23.764706,35.294118,267.764706,1.764706,0.588235,1.823529,-12.235294,0.117647,0.058824,282.882353,119.000000,12.941176,0.176471,10.764706,5.294118,3.117647,0.705882,6.664496,1.792896,18.457647,17,George Pickens,2025,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,NaN,5.470588,8.058824,84.058824,0.529412,0.235294,0.000000,91.000000,28.176471,4.294118,0.058824,3.647059,2.000000,1.294118,0.235294,0.322092,0.563192,0.000000,0.000000,0.000000,0.000000,0.000000,17.170588,17
279,7,Justin Jefferson,2026,2025,27,MIN,Kyler Murray,2025,29,Jauan Jennings,2025,29,NaN,NaN,Justin Jefferson,2025.0,0.117647,0.411765,0.000000,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,-0.028360,4.941176,8.294118,61.647059,0.117647,0.000000,0.000000,84.588235,26.529412,2.764706,0.000000,3.058824,1.470588,0.705882,0.117647,0.401469,0.741072,0.000000,0.000000,0.000000,0.000000,0.000000,11.852941,17.0,Kyler Murray,2025,22.000000,32.200000,192.400000,1.200000,0.600000,3.200000,-22.200000,0.000000,0.000000,188.200000,109.000000,10.000000,0.000000,7.800000,3.400000,1.400000,0.400000,1.144118,-0.084823,15.556000,5,Jauan Jennings,2025,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,NaN,3.666667,6.000000,42.866667,0.600000,0.066667,0.066667,60.333333,12.066667,2.400000,0.066667,2.000000,0.800000,0.600000,0.066667,0.255767,0.477885,0.000000,0.000000,0.000000,0.000000,0.000000,11.553333,15
280,8,A.J. Brown,2026,2025,29,NE,Drake Maye,2025,23,Romeo Doubs,2025,26,NaN,NaN,A.J. Brown,2025.0,0.000000,0.000000,0.000000,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,NaN,5.200000,8.066667,66.866667,0.466667,0.000000,0.000000,95.000000,17.866667,3.133333,0.000000,2.666667,1.666667,0.933333,0.066667,0.355210,0.678490,0.000000,0.000000,0.000000,0.000000,0.000000,14.686667,15.0,Drake Maye,2025,20.823529,28.941176,258.470588,1.823529,0.470588,2.764706,-11.823529,0.352941,0.176471,264.294118,102.705882,11.941176,0.058824,10.470588,5.823529,3.941176,0.352941,9.715385,12.160739,20.703529,17,Romeo Doubs,2025,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,NaN,3.437500,5.312500,45.250000,0.375000,0.062500,0.000000,67.812500,10.187500,2.562500,0.062500,1.875000,1.125000,0.750000,0.125000,0.280438,0.479481,0.000000,0.937500,5.875000,0.000000,0.000000,10.337500,16
281,9,Rashee Rice,2026,2025,26,KC,Patrick Mahomes,2025,30,Xavier Worthy,2025,23,NaN,NaN,Rashee Rice,2025.0,0.625000,2.500000,0.125000,0.125,0.0,0.250000,0.0,0.000000,0.000000,0.000000,0.0000,0.620834,6.625000,9.750000,71.375000,0.625000,0.125000,0.000000,42.250000,51.750000,3.500000,0.125000,2.625000,1.375000,1.125000,0.250000,0.136998,0.531395,0.000000,0.000000,0.000000,0.000000,0.000000,18.762500,8.0,Patrick Mahomes,2025,22.500000,35.857143,256.214286,1.571429,0.785714,2.428571,-13.785714,0.214286,0.000000,289.285714,135.357143,12.357143,0.142857,10.428571,5.142857,3.500000,0.571429,4.874781,0.137742,20.405714,14,Xavier Worthy,2025,0.785714,6.214286,0.000000,0.000000,0.000000,0.285714,0.0,0.214286,0.214286,0.071429,0.0000,0.398310,3.000000,5.214286,38.000000,0.071429,0.000000,0.000000,67.428571,13.785714,1.571429,0.000000,1.428571,0.785714,0.642857,0.071429,0.267594,0.428170,0.000000,0.071429,0.000000,0.000000,0.000000,7.850000,14
282,10,George Pickens,2026,2025,25,DAL,Dak Prescott,2025,33,CeeDee Lamb,2025,27,NaN,NaN,George Pickens,2025.0,0.000000,0.000000,0.000000,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,NaN,5.470588,8.058824,84.058824,0.529412,0.235294,0.000000,91.000000,28.176471,4.294118,0.058824,3.647059,2.000000,1.294118,0.235294,0.322092,0.563192,0.000000,0.000000,0.000000,0.000000,0.000000,17.170588,17.0,Dak Prescott,2025,23.764706,35.294118,267.764706,1.764706,0.588235,1.823529,-12.235294,0.117647,0.058824,282.882353,119.000000,12.941176,0.176471,10.764706,5.294118,3.117647,0.705882,6.664496,1.792896,18.457647,17,CeeDee Lamb,2025,0.076923,0.153846,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,-0.247851,5.769231,9.000000,82.846154,0.230769,0.000000,0.000000,107.923077,24.846154,3.307692,0.000000,3.230769,1.923077,1.230769,0.230769,0.334998,0.611045,0.000000,0.000000,0.000000,0.000000,0.000000,15.453846,13
283,11,Chris Olave,2026,2025,26,NO,Tyler Shough,2025,26,Devaughn Vele,2025,27,NaN,NaN,Chris Olave,2025.0,0.062500,-0.187500,0.000000,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,-1.253102,6.250000,9.750000,72.687500,0.562500,0.000000,0.000000,115.062500,18.062500,3.312500,0.000000,2.625000,1.375000,0.687500,0.250000,0.409910,0.724622,0.000000,0.000000,0.000000,0.000000,0.000000,16.750000,16.0,Tyler Shough,2025,20.090909,29.727273,216.727273,0.909091,0.545455,2.818182,-17.727273,0.181818,0.090909,246.181818,95.545455,9.727273,0.000000,9.454545,4.090909,1.727273,0.272727,0.187267,-2.748456,14.360000,11,Devaughn Vele,2025,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,NaN,2.777778,4.333333,32.555556,0.222222,0.000000,0.000000,48.000000,3.777778,2.111111,0.000000,2.111111,0.333333,0.000000,0.000000,0.179649,0.325708,0.000000,0.000000,0.000000,0.000000,0.000000,7.366667,9
284,12,Nico Collins,2026,2025,27,HOU,C.J. Stroud,2025,24,Jayden Higgins,2025,22,NaN,NaN,Nico Collins,2025.0,0.133333,1.000000,0.066667,0.000,0.0,0.066667,0.0,0.000000,0.000000,0.000000,0.0000,0.997755,4.733333,8.000000,74.466667,0.400000,0.066667,0.066667,101.933333,21.600000,3.200000,0.066667,3.066667,2.000000,1.200000,0.333333,0.350744,0.609152,0.000000,0.000000,0.000000,0.000000,0.000000,15.080000,15.0,C.J. Stroud,2025,19.500000,30.214286,217.214286,1.357143,0.571429,1.642857,-13.500000,0.000000,0.000000,243.214286,97.500000,9.714286,0.000000,8.000000,4.285714,2.785714,0.714286,3.404371,0.208301,14.895714,14,Jayden Higgins,2025,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,NaN,2.411765,4.000000,30.882353,0.352941,0.000000,0.000000,49.352941,7.235294,1.647059,0.000000,1.352941,0.529412,0.294118,0.058824,0.176581,0.309304,0.000000,0.000000,0.000000,0.000000,0.000000,7.617647,17
285,13,Garrett Wilson,2026,2025,26,NYJ,Geno Smith,2025,35,Allen Lazard,2025,31,NaN,NaN,Garrett Wilson,2025.0,0.000000,0.000000,0.000000,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,NaN,5.142857,8.428571,56.428571,0.571429,0.142857,0.000000,76.428571,14.285714,2.571429,0.000000,2.142857,1.285714,0.571429,0.000000,0.562568,0.924637,0.000000,0.000000,0.000000,0.000000,0.000000,14.214286,7.0,Geno Smith,2025,20.133333,29.866667,201.666667,1.266667,1.133333,3.666667,-27.000000,0.200000,0.066667,184.133333,114.200000,9.866667,0.066667,7.733333,3.533333,2.200000,0.200000,-4.861427,1.279700,11.593333,15,Allen Lazard,2025,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,NaN,1.111111,2.000000,7.777778,0.111111,0.000000,0.000000,15.777778,3.666667,0.444444,0.000000,0.111111,0.000000,0.000000,0.000000,0.057290,0.134897,0.000000,0.000000,0.000000,0.000000,0.000000,2.555556,9
286,14,Zay Flowers,2026,2025,26,BAL,Lamar Jackson,2025,29,Rashod Bateman,2025,27,NaN,NaN,Zay Flowers,2025.0,0.588235,3.647059,0.058824,0.000,0.0,0.176471,0.0,0.117647,0.058824,0.000000,0.0000,0.312457,5.058824,6.941176,71.235294,0.294118,0.176471,0.176471,70.823529,26.941176,2.823529,0.000000,2.529412,1.647059,1.117647,0.235294,0.360479,0.700561,0.000000,0.000000,0.000000,0.000000,0.000000,14.311765,17.0,Lamar Jackson,2025,14.769231,23.230769,196.076923,1.615385,0.538462,2.769231,-18.384615,0.384615,0.230769,203.692308,81.846154,8.384615,0.076923,7.461538,4.384615,2.923077,0.461538,1.396694,2.905986,16.527692,13,Rashod Bateman,2025,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,NaN,1.461538,2.923077,17.230769,0.153846,0.000000,0.000000,36.000000,3.000000,0.923077,0.076923,0.769231,0.384615,0.230769,0.000000,0.174617,0.301390,0.000000,0.000000,0.000000,0.000000,0.000000,4.261538,13
287,15,DeVonta Smith,2026,2025,28,PHI,Jalen Hurts,2025,28,Dontayvion Wicks,2025,25,NaN,NaN,DeVonta Smith,2025.0,0.000000,0.000000,0.000000,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,NaN,4.529412,6.647059,59.294118,0.235294,0.000000,0.000000,79.705882,17.235294,2.588235,0.000000,2.117647,1.352941,0.823529,0.235294,0.321282,0.593545,0.000000,0.000000,0.000000,0.000000,0.000000,11.870588,17.0,Jalen Hurts,2025,18.375000,28.375000,201.500000,1.562500,0.375000,2.000000,-11.312500,0.187500,0.062500,254.500000,79.062500,9.375000,0.000000,7.312500,4.187500,2.500000,0.562500,2.144653,4.227860,18.816250,16,Dontayvion Wicks,2025,0.076923,0.461538,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,0.494141,2.307692,3.538462,25.538462,0.153846,0.000000,0.000000,39.769231,5.153846,1.615385,0.000000,1.153846,0.615385,0.230769,0.000000,0.168810,0.310370,0.000000,0.000000,0.000000,0.000000,0.000000,5.830769,13
288,16,Tetairoa McMillan,2026,2025,23,CAR,Bryce Young,2025,25,Xavier Legette,2025,25,NaN,NaN,Tetairoa McMillan,2025.0,0.000000,0.000000,0.000000,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,NaN,4.117647,7.176471,59.647059,0.411765,0.000000,0.000000,82.941176,15.823529,3.235294,0.000000,2.764706,1.588235,1.000000,0.176471,0.459451,0.707719,0.000000,0.000000,0.000000,0.000000,0.000000,12.552941,17.0,Bryce Young,2025,19.000000,29.875000,188.187500,1.437500,0.687500,1.687500,-12.625000,0.187500,0.125000,193.875000,96.187500,9.562500,0.062500,7.125000,3.437500,2.437500,0.250000,-1.373307,1.271870,13.627500,16,Xavier Legette,2025,0.066667,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0000,-0.530516,2.333333,4.266667,24.200000,0.200000,0.066667,0.000000,42.200000,5.000000,1.200000,0.000000,0.933333,0.466667,0.466667,0.000000,0.196893,0.352280,0.000000,0.000000,0.000000,0.000000,0.000000,5.953333,15

In [134]:
mask = final_wr["player_display_name"].isna() & (final_wr["season"] < 2026)

final_wr.loc[mask, "player_display_name"] = final_wr.loc[mask, "player_name"]
final_wr.loc[mask, "fantasy_points_ppr_pg"] = 0

The code above imputes a zero for players that genuinely scored no fantasy points that season in Brandon Aiyuk and Diontae Johnson.

In [137]:
cols = [
    "Previous_rushing_epa_pg",
    "QB_passing_cpoe_pg",
    "Teammate_rushing_epa_pg"
]

final_wr[cols] = final_wr[cols].fillna(0)

Imputes a zero for any final null values.

In [138]:
final_wr.isnull().sum()

preseason_rank                              0
player_name                                 0
season                                      0
past_season                                 0
player_age                                  0
team                                        0
team_qb                                     0
team_qb_season                              0
team_qb_age                                 0
teammate                                    0
teammate_season                             0
teammate_age                                0
player_display_name                        56
fantasy_points_ppr_pg                      56
Previous_player_display_name                0
Previous_season                             0
Previous_carries_pg                         0
Previous_rushing_yards_pg                   0
Previous_rushing_tds_pg                     0
Previous_rushing_fumbles_pg                 0
Previous_rushing_fumbles_lost_pg            0
Previous_rushing_first_downs_pg             0
Previous_rushing_2pt_conversions_pg         0
Previous_rushing_10_pg                      0
Previous_rushing_12_pg                      0
Previous_rushing_20_pg                      0
Previous_rushing_40_pg                      0
Previous_rushing_epa_pg                     0
Previous_receptions_pg                      0
Previous_targets_pg                         0
Previous_receiving_yards_pg                 0
Previous_receiving_tds_pg                   0
Previous_receiving_fumbles_pg               0
Previous_receiving_fumbles_lost_pg          0
Previous_receiving_air_yards_pg             0
Previous_receiving_yards_after_catch_pg     0
Previous_receiving_first_downs_pg           0
Previous_receiving_2pt_conversions_pg       0
Previous_receiving_10_pg                    0
Previous_receiving_16_pg                    0
Previous_receiving_20_pg                    0
Previous_receiving_40_pg                    0
Previous_air_yards_share_pg                 0
Previous_wopr_pg                            0
Previous_special_teams_tds_pg               0
Previous_punt_returns_pg                    0
Previous_punt_return_yards_pg               0
Previous_kickoff_returns_pg                 0
Previous_kickoff_return_yards_pg            0
Previous_fantasy_points_ppr_pg              0
Previous_games_played                       0
QB_player_display_name                      0
QB_season                                   0
QB_completions_pg                           0
QB_attempts_pg                              0
QB_passing_yards_pg                         0
QB_passing_tds_pg                           0
QB_passing_interceptions_pg                 0
QB_sacks_suffered_pg                        0
QB_sack_yards_lost_pg                       0
QB_sack_fumbles_pg                          0
QB_sack_fumbles_lost_pg                     0
QB_passing_air_yards_pg                     0
QB_passing_yards_after_catch_pg             0
QB_passing_first_downs_pg                   0
QB_passing_2pt_conversions_pg               0
QB_passing_10_pg                            0
QB_passing_16_pg                            0
QB_passing_20_pg                            0
QB_passing_40_pg                            0
QB_passing_epa_pg                           0
QB_passing_cpoe_pg                          0
QB_fantasy_points_ppr_pg                    0
QB_games_played                             0
Teammate_player_display_name                0
Teammate_season                             0
Teammate_carries_pg                         0
Teammate_rushing_yards_pg                   0
Teammate_rushing_tds_pg                     0
Teammate_rushing_fumbles_pg                 0
Teammate_rushing_fumbles_lost_pg            0
Teammate_rushing_first_downs_pg             0
Teammate_rushing_2pt_conversions_pg         0
Teammate_rushing_10_pg                      0
Teammate_rushing_12_pg                      0
Teammate_rushing_20_pg                      0
Teammate_rushing_40_pg                      0
Teammate_rushing_epa_pg                     0
Teammate_receptions_pg                      0
Teammate_targets_pg                         0
Teammate_receiving_yards_pg                 0
Teammate_receiving_tds_pg                   0
Teammate_receiving_fumbles_pg               0
Teammate_receiving_fumbles_lost_pg          0
Teammate_receiving_air_yards_pg             0
Teammate_receiving_yards_after_catch_pg     0
Teammate_receiving_first_downs_pg           0
Teammate_receiving_2pt_conversions_pg       0
Teammate_receiving_10_pg                    0
Teammate_receiving_16_pg                    0
Teammate_receiving_20_pg                    0
Teammate_receiving_40_pg                    0
Teammate_air_yards_share_pg                 0
Teammate_wopr_pg                            0
Teammate_special_teams_tds_pg               0
Teammate_punt_returns_pg                    0
Teammate_punt_return_yards_pg               0
Teammate_kickoff_returns_pg                 0
Teammate_kickoff_return_yards_pg            0
Teammate_fantasy_points_ppr_pg              0
Teammate_games_played                       0
dtype: int64

The remaining nulls are just 2026 players that we don't know the result for yet in terms of PPR fantasy points per game.

#### Final Cleaned Dataset

In [139]:
final_wr.to_csv('../outputs/final_wrs_model_data_2020_2026.csv', index=False)

### Manual Input Dataset - RB

This dataset was put together from Claude and QA'd. It has the top 60 non-rookie RBs from 2021-2026, as well as that player's preseason projected QB and projected best WR teammate as well as their ages.

In [120]:
fantasy_board = pd.read_csv('../inputs/top60_preseason_rb_ppr_2021_2026.csv')

In [63]:
fantasy_board.head()

,preseason_rank,player_name,season,past_season,player_age,team,team_qb,team_qb_season,team_qb_age,teammate,teammate_season,teammate_age
0,1,Christian McCaffrey,2021,2020,25,CAR,Sam Darnold,2020,24,Royce Freeman,2020,25
1,2,Dalvin Cook,2021,2020,26,MIN,Kirk Cousins,2020,33,Alexander Mattison,2020,22
2,3,Alvin Kamara,2021,2020,26,NO,Jameis Winston,2020,27,Tony Jones,2020,24
3,4,Derrick Henry,2021,2020,27,TEN,Ryan Tannehill,2020,33,D'Onta Foreman,2020,25
4,5,Ezekiel Elliott,2021,2020,26,DAL,Dak Prescott,2020,28,Tony Pollard,2020,24

In [121]:
fantasy_board['player_name'] = (
    fantasy_board['player_name']
    .str.replace(r'\s+(Jr\.?|Sr\.?|II|III|IV|V)$', '', regex=True)
)

fantasy_board['team_qb'] = (
    fantasy_board['team_qb']
    .str.replace(r'\s+(Jr\.?|Sr\.?|II|III|IV|V)$', '', regex=True)
)

fantasy_board['teammate'] = (
    fantasy_board['teammate']
    .str.replace(r'\s+(Jr\.?|Sr\.?|II|III|IV|V)$', '', regex=True)
)

In [122]:
temp_rb_1 = pd.merge(fantasy_board, target, left_on=['player_name', 'season'], 
                   right_on=['player_display_name', 'season'], how='left')

In [123]:
temp_rb_2 = pd.merge(temp_rb_1, player_previous_seasonal, left_on=['player_name', 'past_season'], 
                   right_on=['Previous_player_display_name', 'Previous_season'], how='left')

In [124]:
temp_rb_3 = pd.merge(temp_rb_2, qb_seasonal, left_on=['team_qb', 'team_qb_season'], 
                   right_on=['QB_player_display_name', 'QB_season'], how='left')

In [125]:
final_rb = pd.merge(temp_rb_3, teammate_seasonal, left_on=['teammate', 'teammate_season'], 
                   right_on=['Teammate_player_display_name', 'Teammate_season'], how='left')

In [50]:
final_rb.head()

,preseason_rank,player_name,season,past_season,player_age,team,team_qb,team_qb_season,team_qb_age,teammate,teammate_season,teammate_age,player_display_name,fantasy_points_ppr_pg,Previous_player_display_name,Previous_season,Previous_carries_pg,Previous_rushing_yards_pg,Previous_rushing_tds_pg,Previous_rushing_fumbles_pg,Previous_rushing_fumbles_lost_pg,Previous_rushing_first_downs_pg,Previous_rushing_2pt_conversions_pg,Previous_rushing_10_pg,Previous_rushing_12_pg,Previous_rushing_20_pg,Previous_rushing_40_pg,Previous_rushing_epa_pg,Previous_receptions_pg,Previous_targets_pg,Previous_receiving_yards_pg,Previous_receiving_tds_pg,Previous_receiving_fumbles_pg,Previous_receiving_fumbles_lost_pg,Previous_receiving_air_yards_pg,Previous_receiving_yards_after_catch_pg,Previous_receiving_first_downs_pg,Previous_receiving_2pt_conversions_pg,Previous_receiving_10_pg,Previous_receiving_16_pg,Previous_receiving_20_pg,Previous_receiving_40_pg,Previous_air_yards_share_pg,Previous_wopr_pg,Previous_special_teams_tds_pg,Previous_punt_returns_pg,Previous_punt_return_yards_pg,Previous_kickoff_returns_pg,Previous_kickoff_return_yards_pg,Previous_fantasy_points_ppr_pg,Previous_games_played,QB_player_display_name,QB_season,QB_completions_pg,QB_attempts_pg,QB_passing_yards_pg,QB_passing_tds_pg,QB_passing_interceptions_pg,QB_sacks_suffered_pg,QB_sack_yards_lost_pg,QB_sack_fumbles_pg,QB_sack_fumbles_lost_pg,QB_passing_air_yards_pg,QB_passing_yards_after_catch_pg,QB_passing_first_downs_pg,QB_passing_2pt_conversions_pg,QB_passing_10_pg,QB_passing_16_pg,QB_passing_20_pg,QB_passing_40_pg,QB_passing_epa_pg,QB_passing_cpoe_pg,QB_fantasy_points_ppr_pg,QB_games_played,Teammate_player_display_name,Teammate_season,Teammate_carries_pg,Teammate_rushing_yards_pg,Teammate_rushing_tds_pg,Teammate_rushing_fumbles_pg,Teammate_rushing_fumbles_lost_pg,Teammate_rushing_first_downs_pg,Teammate_rushing_2pt_conversions_pg,Teammate_rushing_10_pg,Teammate_rushing_12_pg,Teammate_rushing_20_pg,Teammate_rushing_40_pg,Teammate_rushing_epa_pg,Teammate_receptions_pg,Teammate_targets_pg,Teammate_receiving_yards_pg,Teammate_receiving_tds_pg,Teammate_receiving_fumbles_pg,Teammate_receiving_fumbles_lost_pg,Teammate_receiving_air_yards_pg,Teammate_receiving_yards_after_catch_pg,Teammate_receiving_first_downs_pg,Teammate_receiving_2pt_conversions_pg,Teammate_receiving_10_pg,Teammate_receiving_16_pg,Teammate_receiving_20_pg,Teammate_receiving_40_pg,Teammate_air_yards_share_pg,Teammate_wopr_pg,Teammate_special_teams_tds_pg,Teammate_punt_returns_pg,Teammate_punt_return_yards_pg,Teammate_kickoff_returns_pg,Teammate_kickoff_return_yards_pg,Teammate_fantasy_points_ppr_pg,Teammate_games_played
0,1,Christian McCaffrey,2021,2020,25,CAR,Sam Darnold,2020,24,Royce Freeman,2020,25,Christian McCaffrey,18.214286,Christian McCaffrey,2020.0,19.666667,75.000000,1.666667,0.000000,0.000000,4.666667,0.000000,1.333333,1.000000,0.000000,0.000000,1.311211,5.666667,6.333333,49.666667,0.333333,0.000000,0.000000,9.000000,41.000000,2.666667,0.000000,1.666667,0.666667,0.333333,0.000000,0.032048,0.257394,0.0,0.000000,0.0,0.000000,0.000000,30.133333,3.0,Sam Darnold,2020.0,18.083333,30.333333,184.0000,0.7500,0.916667,2.916667,-19.500000,0.333333,0.166667,232.833333,96.250000,9.083333,0.083333,7.250000,3.833333,2.250,0.166667,-6.404763,-1.828693,11.168333,12.0,Royce Freeman,2020.0,3.181818,15.454545,0.000000,0.0,0.0,0.909091,0.0,0.454545,0.272727,0.181818,0.000,-0.026375,1.090909,1.181818,7.363636,0.000000,0.0,0.0,2.000000,5.727273,0.363636,0.0,0.272727,0.090909,0.090909,0.0,0.005844,0.053940,0.0,0.0,0.0,0.0,0.000,3.372727,11.0
1,2,Dalvin Cook,2021,2020,26,MIN,Kirk Cousins,2020,33,Alexander Mattison,2020,22,Dalvin Cook,15.869231,Dalvin Cook,2020.0,22.285714,111.214286,1.142857,0.285714,0.142857,6.500000,0.214286,3.285714,2.285714,0.428571,0.071429,1.153851,3.142857,3.857143,25.785714,0.071429,0.071429,0.071429,-6.857143,31.285714,1.214286,0.000000,1.000000,0.357143,0.285714,0.071429,-0.058278,0.158838,0.0,0.000000,0.0,0.000000,0.000000,24.128571,14.0,Kirk Cousins,2020.0,21.812500,32.250000,266.5625,2.1875,0.812500,2.437500,-16.000000,0.500000,0.250000,256.437500,121.000000,13.250000,0.312500,10.875000,5.375000,3.625,0.437500,5.875464,4.268654,19.137500,16.0,Alexander Mattison,2020.0,7.384615,33.384615,0.153846,0.0,0.0,1.846154,0.0,0.923077,0.769231,0.307692,0.000,-0.557275,1.000000,1.153846,9.615385,0.076923,0.0,0.0,3.153846,8.307692,0.384615,0.0,0.307692,0.076923,0.076923,0.0,0.010563,0.064548,0.0,0.0,0.0,0.0,0.000,6.684615,13.0
2,3,Alvin Kamara,2021,2020,26,NO,Jameis Winston,2020,27,Tony Jones,2020,24,Alvin Kamara,18.053846,Alvin Kamara,2020.0,12.466667,62.133333,1.066667,0.066667,0.000000,3.866667,0.000000,1.800000,1.066667,0.466667,0.133333,0.601670,5.533333,7.133333,50.400000,0.333333,0.000000,0.000000,4.000000,48.733333,2.333333,0.000000,1.933333,0.866667,0.600000,0.133333,0.008836,0.331254,0.0,0.066667,0.0,0.133333,2.933333,25.186667,15.0,Jameis Winston,2020.0,2.333333,3.666667,25.0000,0.0000,0.000000,0.666667,-3.666667,0.000000,0.000000,17.000000,20.333333,1.666667,0.000000,1.666667,0.333333,0.000,0.000000,0.400031,10.963377,0.800000,3.0,Tony Jones,2020.0,3.000000,13.000000,0.000000,0.0,0.0,1.000000,0.0,0.000000,0.000000,0.000000,0.000,0.428658,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000,1.300000,1.0
3,4,Derrick Henry,2021,2020,27,TEN,Ryan Tannehill,2020,33,D'Onta Foreman,2020,25,Derrick Henry,24.162500,Derrick Henry,2020.0,23.625000,126.687500,1.062500,0.187500,0.125000,6.125000,0.062500,3.000000,2.375000,1.000000,0.250000,2.109465,1.187500,1.937500,7.125000,0.000000,0.000000,0.000000,-1.812500,7.937500,0.250000,0.000000,0.062500,0.062500,0.062500,0.062500,-0.011091,0.092364,0.0,0.000000,0.0,0.000000,0.000000,20.818750,16.0,Ryan Tannehill,2020.0,19.687500,30.062500,238.6875,2.0625,0.437500,1.500000,-10.812500,0.312500,0.062500,251.500000,95.562500,12.625000,0.062500,9.562500,4.687500,2.750,0.812500,7.889777,1.977874,21.522500,16.0,D'Onta Foreman,2020.0,4.400000,19.000000,0.000000,0.0,0.0,1.200000,0.0,0.600000,0.400000,0.000000,0.000,-0.530724,0.200000,0.200000,1.000000,0.200000,0.0,0.0,0.400000,0.600000,0.200000,0.0,0.000000,0.000000,0.000000,0.0,0.002030,0.012532,0.0,0.0,0.0,0.0,0.000,3.400000,5.0
4,5,Ezekiel Elliott,2021,2020,26,DAL,Dak Prescott,2020,28,Tony Pollard,2020,24,Ezekiel Elliott,14.827059,Ezekiel Elliott,2020.0,16.266667,65.266667,0.400000,0.333333,0.266667,4.133333,0.000000,1.466667,0.866667,0.200000,0.000000,-1.920434,3.466667,4.733333,22.533333,0.133333,0.066667,0.066667,-1.133333,24.000000,1.333333,0.066667,0.933333,0.200000,0.000000,0.000000,-0.000548,0.171612,0.0,0.000000,0.0,0.000000,0.000000,14.913333,15.0,Dak Prescott,2020.0,30.200000,44.400000,371.2000,1.8000,0.800000,2.000000,-13.200000,0.600000,0.600000,352.400000,162.000000,18.600000,0.200000,16.600000,7.400000,5.000,1.200000,6.424759,-0.476596,27.128000,5.0,Tony Pollard,2020.0,6.312500,27.187500,0.250000,0.0,0.0,1.437500,0.0,0.625000,0.625000,0.250000,0.125,-0.169213,1.750000,2.500000,12.062500,0.062500,0.0,0.0,-0.875000,14.500000,0.562500,0.0,0.500000,0.187500,0.062500,0.0,-0.002596,0.102278,0.0,0.0,0.0,2.0,47.875,7.550000,16.0

**Data Cleaning**

Find players that did not have joined data because of formatting issues in names (capitalization, apostrophes, etc.) and change the name in the manual csv file. 

Once done, players with player_display_name NaN mean that they did not record any stats that season. Impute a zero for fantasy_points_ppr_pg.

Same with teammate_player_display_name.

Then rerun the isnull code and impute zeroes for anything remaining (not including fantasy points per game for 2026 rookies).

Gus Edwards (2021), ELijah Mitchell (2024), Joe Mixon (2025), and MarShawn Lloyd (2025) have missing values in the join because they did not play at all during the season. I will remove these rows.

In [126]:
# View all rows where player_display_name is null
null_players_teammate = final_rb[final_rb['Teammate_player_display_name'].isna()]

null_players_teammate

,preseason_rank,player_name,season,past_season,player_age,team,team_qb,team_qb_season,team_qb_age,teammate,teammate_season,teammate_age,player_display_name,fantasy_points_ppr_pg,Previous_player_display_name,Previous_season,Previous_carries_pg,Previous_rushing_yards_pg,Previous_rushing_tds_pg,Previous_rushing_fumbles_pg,Previous_rushing_fumbles_lost_pg,Previous_rushing_first_downs_pg,Previous_rushing_2pt_conversions_pg,Previous_rushing_10_pg,Previous_rushing_12_pg,Previous_rushing_20_pg,Previous_rushing_40_pg,Previous_rushing_epa_pg,Previous_receptions_pg,Previous_targets_pg,Previous_receiving_yards_pg,Previous_receiving_tds_pg,Previous_receiving_fumbles_pg,Previous_receiving_fumbles_lost_pg,Previous_receiving_air_yards_pg,Previous_receiving_yards_after_catch_pg,Previous_receiving_first_downs_pg,Previous_receiving_2pt_conversions_pg,Previous_receiving_10_pg,Previous_receiving_16_pg,Previous_receiving_20_pg,Previous_receiving_40_pg,Previous_air_yards_share_pg,Previous_wopr_pg,Previous_special_teams_tds_pg,Previous_punt_returns_pg,Previous_punt_return_yards_pg,Previous_kickoff_returns_pg,Previous_kickoff_return_yards_pg,Previous_fantasy_points_ppr_pg,Previous_games_played,QB_player_display_name,QB_season,QB_completions_pg,QB_attempts_pg,QB_passing_yards_pg,QB_passing_tds_pg,QB_passing_interceptions_pg,QB_sacks_suffered_pg,QB_sack_yards_lost_pg,QB_sack_fumbles_pg,QB_sack_fumbles_lost_pg,QB_passing_air_yards_pg,QB_passing_yards_after_catch_pg,QB_passing_first_downs_pg,QB_passing_2pt_conversions_pg,QB_passing_10_pg,QB_passing_16_pg,QB_passing_20_pg,QB_passing_40_pg,QB_passing_epa_pg,QB_passing_cpoe_pg,QB_fantasy_points_ppr_pg,QB_games_played,Teammate_player_display_name,Teammate_season,Teammate_carries_pg,Teammate_rushing_yards_pg,Teammate_rushing_tds_pg,Teammate_rushing_fumbles_pg,Teammate_rushing_fumbles_lost_pg,Teammate_rushing_first_downs_pg,Teammate_rushing_2pt_conversions_pg,Teammate_rushing_10_pg,Teammate_rushing_12_pg,Teammate_rushing_20_pg,Teammate_rushing_40_pg,Teammate_rushing_epa_pg,Teammate_receptions_pg,Teammate_targets_pg,Teammate_receiving_yards_pg,Teammate_receiving_tds_pg,Teammate_receiving_fumbles_pg,Teammate_receiving_fumbles_lost_pg,Teammate_receiving_air_yards_pg,Teammate_receiving_yards_after_catch_pg,Teammate_receiving_first_downs_pg,Teammate_receiving_2pt_conversions_pg,Teammate_receiving_10_pg,Teammate_receiving_16_pg,Teammate_receiving_20_pg,Teammate_receiving_40_pg,Teammate_air_yards_share_pg,Teammate_wopr_pg,Teammate_special_teams_tds_pg,Teammate_punt_returns_pg,Teammate_punt_return_yards_pg,Teammate_kickoff_returns_pg,Teammate_kickoff_return_yards_pg,Teammate_fantasy_points_ppr_pg,Teammate_games_played
13,14,David Montgomery,2021,2020,24,CHI,Andy Dalton,2020,34,Damien Williams,2020,28,David Montgomery,15.0,David Montgomery,2020.0,16.466667,71.333333,0.533333,0.0000,0.0000,3.933333,0.066667,1.6000,0.8000,0.333333,0.133333,-0.600822,3.600,4.533333,29.20,0.133333,0.066667,0.066667,4.266667,26.4000,1.666667,0.0,1.333333,0.466667,0.133333,0.000,0.012908,0.188074,0.0,0.0,0.0,0.0,0.0,17.653333,15.0,Andy Dalton,2020.0,19.636364,30.272727,197.272727,1.272727,0.727273,2.181818,-16.727273,0.090909,0.000000,208.090909,94.818182,10.545455,0.000000,7.818182,2.818182,1.818182,0.454545,-1.018261,0.032265,12.445455,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,Raheem Mostert,2021,2020,29,SF,Jimmy Garoppolo,2020,29,Elijah Mitchell,2020,24,Raheem Mostert,2.0,Raheem Mostert,2020.0,13.000000,65.125000,0.250000,0.1250,0.1250,2.750000,0.000000,1.3750,0.8750,0.250000,0.125000,-1.328639,2.000,2.375000,19.50,0.125000,0.000000,0.000000,2.500000,17.0000,0.625000,0.0,0.375000,0.125000,0.125000,0.125,0.007858,0.109359,0.0,0.0,0.0,0.0,0.0,12.462500,8.0,Jimmy Garoppolo,2020.0,15.666667,23.333333,182.666667,1.166667,0.833333,1.833333,-12.833333,0.166667,0.000000,146.500000,119.000000,9.166667,0.000000,7.666667,3.666667,1.666667,0.500000,4.145929,0.680168,10.723333,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,16,David Montgomery,2023,2022,26,DET,Jared Goff,2022,28,Jahmyr Gibbs,2022,21,David Montgomery,14.8,David Montgomery,2022.0,12.562500,50.062500,0.312500,0.0625,0.0625,2.562500,0.000000,1.0625,0.6875,0.125000,0.000000,-0.957087,2.125,2.500000,19.75,0.062500,0.062500,0.062500,3.187500,17.6875,0.625000,0.0,0.687500,0.375000,0.312500,0.000,0.017420,0.195272,0.0,0.0,0.0,0.0,0.0,11.106250,16.0,Jared Goff,2022.0,22.470588,34.529412,261.058824,1.705882,0.411765,1.352941,-9.176471,0.294118,0.176471,242.882353,134.411765,13.352941,0.058824,10.647059,5.058824,3.352941,0.705882,6.001040,-1.499733,16.724706,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [127]:
# View all rows where player_display_name is null
null_players_qb = final_rb[final_rb['QB_player_display_name'].isna()]

null_players_qb

,preseason_rank,player_name,season,past_season,player_age,team,team_qb,team_qb_season,team_qb_age,teammate,teammate_season,teammate_age,player_display_name,fantasy_points_ppr_pg,Previous_player_display_name,Previous_season,Previous_carries_pg,Previous_rushing_yards_pg,Previous_rushing_tds_pg,Previous_rushing_fumbles_pg,Previous_rushing_fumbles_lost_pg,Previous_rushing_first_downs_pg,Previous_rushing_2pt_conversions_pg,Previous_rushing_10_pg,Previous_rushing_12_pg,Previous_rushing_20_pg,Previous_rushing_40_pg,Previous_rushing_epa_pg,Previous_receptions_pg,Previous_targets_pg,Previous_receiving_yards_pg,Previous_receiving_tds_pg,Previous_receiving_fumbles_pg,Previous_receiving_fumbles_lost_pg,Previous_receiving_air_yards_pg,Previous_receiving_yards_after_catch_pg,Previous_receiving_first_downs_pg,Previous_receiving_2pt_conversions_pg,Previous_receiving_10_pg,Previous_receiving_16_pg,Previous_receiving_20_pg,Previous_receiving_40_pg,Previous_air_yards_share_pg,Previous_wopr_pg,Previous_special_teams_tds_pg,Previous_punt_returns_pg,Previous_punt_return_yards_pg,Previous_kickoff_returns_pg,Previous_kickoff_return_yards_pg,Previous_fantasy_points_ppr_pg,Previous_games_played,QB_player_display_name,QB_season,QB_completions_pg,QB_attempts_pg,QB_passing_yards_pg,QB_passing_tds_pg,QB_passing_interceptions_pg,QB_sacks_suffered_pg,QB_sack_yards_lost_pg,QB_sack_fumbles_pg,QB_sack_fumbles_lost_pg,QB_passing_air_yards_pg,QB_passing_yards_after_catch_pg,QB_passing_first_downs_pg,QB_passing_2pt_conversions_pg,QB_passing_10_pg,QB_passing_16_pg,QB_passing_20_pg,QB_passing_40_pg,QB_passing_epa_pg,QB_passing_cpoe_pg,QB_fantasy_points_ppr_pg,QB_games_played,Teammate_player_display_name,Teammate_season,Teammate_carries_pg,Teammate_rushing_yards_pg,Teammate_rushing_tds_pg,Teammate_rushing_fumbles_pg,Teammate_rushing_fumbles_lost_pg,Teammate_rushing_first_downs_pg,Teammate_rushing_2pt_conversions_pg,Teammate_rushing_10_pg,Teammate_rushing_12_pg,Teammate_rushing_20_pg,Teammate_rushing_40_pg,Teammate_rushing_epa_pg,Teammate_receptions_pg,Teammate_targets_pg,Teammate_receiving_yards_pg,Teammate_receiving_tds_pg,Teammate_receiving_fumbles_pg,Teammate_receiving_fumbles_lost_pg,Teammate_receiving_air_yards_pg,Teammate_receiving_yards_after_catch_pg,Teammate_receiving_first_downs_pg,Teammate_receiving_2pt_conversions_pg,Teammate_receiving_10_pg,Teammate_receiving_16_pg,Teammate_receiving_20_pg,Teammate_receiving_40_pg,Teammate_air_yards_share_pg,Teammate_wopr_pg,Teammate_special_teams_tds_pg,Teammate_punt_returns_pg,Teammate_punt_return_yards_pg,Teammate_kickoff_returns_pg,Teammate_kickoff_return_yards_pg,Teammate_fantasy_points_ppr_pg,Teammate_games_played
43,44,Tevin Coleman,2021,2020,28,NYJ,Josh Johnson,2020,34,Ty Johnson,2020,24,Tevin Coleman,4.681818,Tevin Coleman,2020.0,4.666667,8.833333,0.000000,0.000000,0.000000,0.500000,0.0,0.333333,0.166667,0.000000,0.000000,-1.407482,0.666667,0.833333,5.666667,0.000000,0.000000,0.000000,2.166667,3.500000,0.333333,0.0,0.333333,0.166667,0.000000,0.0,0.013912,0.055787,0.0,0.0,0.0,0.000000,0.000000,2.116667,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ty Johnson,2020.0,4.909091,23.090909,0.090909,0.000000,0.000000,1.000000,0.0,0.363636,0.363636,0.090909,0.000000,0.119872,1.454545,1.909091,9.000000,0.090909,0.000000,0.000000,4.818182,11.727273,0.545455,0.0,0.363636,0.090909,0.000000,0.0,0.012004,0.112841,0.0,0.0,0.0,0.454545,8.545455,5.754545,11.0
176,17,Aaron Jones,2025,2024,30,MIN,JJ McCarthy,2024,22,Jordan Mason,2024,26,Aaron Jones,9.891667,Aaron Jones,2024.0,15.000000,66.941176,0.294118,0.176471,0.058824,2.882353,0.0,1.470588,1.176471,0.176471,0.058824,-0.790950,3.000000,3.647059,24.000000,0.117647,0.117647,0.117647,3.176471,24.176471,1.176471,0.0,1.000000,0.411765,0.235294,0.0,0.007210,0.187638,0.0,0.0,0.0,0.000000,0.000000,14.211765,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jordan Mason,2024.0,12.750000,65.750000,0.250000,0.250000,0.083333,3.083333,0.0,1.916667,1.333333,0.750000,0.000000,-0.453533,0.916667,1.166667,7.583333,0.000000,0.000000,0.000000,4.333333,4.916667,0.416667,0.0,0.166667,0.083333,0.083333,0.0,0.013771,0.071024,0.0,0.0,0.0,0.166667,2.416667,9.583333,12.0
192,33,Jordan Mason,2025,2024,26,MIN,JJ McCarthy,2024,22,Aaron Jones,2024,30,Jordan Mason,8.056250,Jordan Mason,2024.0,12.750000,65.750000,0.250000,0.250000,0.083333,3.083333,0.0,1.916667,1.333333,0.750000,0.000000,-0.453533,0.916667,1.166667,7.583333,0.000000,0.000000,0.000000,4.333333,4.916667,0.416667,0.0,0.166667,0.083333,0.083333,0.0,0.013771,0.071024,0.0,0.0,0.0,0.166667,2.416667,9.583333,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Aaron Jones,2024.0,15.000000,66.941176,0.294118,0.176471,0.058824,2.882353,0.0,1.470588,1.176471,0.176471,0.058824,-0.790950,3.000000,3.647059,24.000000,0.117647,0.117647,0.117647,3.176471,24.176471,1.176471,0.0,1.000000,0.411765,0.235294,0.0,0.007210,0.187638,0.0,0.0,0.0,0.000000,0.000000,14.211765,17.0
202,43,Ty Chandler,2025,2024,25,MIN,JJ McCarthy,2024,22,Aaron Jones,2024,30,Ty Chandler,2.933333,Ty Chandler,2024.0,4.000000,13.000000,0.000000,0.000000,0.000000,0.642857,0.0,0.214286,0.142857,0.071429,0.000000,-1.050125,0.428571,0.428571,3.000000,0.000000,0.000000,0.000000,-0.785714,3.785714,0.142857,0.0,0.142857,0.000000,0.000000,0.0,-0.002685,0.023717,0.0,0.0,0.0,0.571429,14.642857,2.028571,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Aaron Jones,2024.0,15.000000,66.941176,0.294118,0.176471,0.058824,2.882353,0.0,1.470588,1.176471,0.176471,0.058824,-0.790950,3.000000,3.647059,24.000000,0.117647,0.117647,0.117647,3.176471,24.176471,1.176471,0.0,1.000000,0.411765,0.235294,0.0,0.007210,0.187638,0.0,0.0,0.0,0.000000,0.000000,14.211765,17.0

In [128]:
# View all rows where player_display_name is null
null_players_previous = final_rb[final_rb['Previous_player_display_name'].isna()]

null_players_previous

,preseason_rank,player_name,season,past_season,player_age,team,team_qb,team_qb_season,team_qb_age,teammate,teammate_season,teammate_age,player_display_name,fantasy_points_ppr_pg,Previous_player_display_name,Previous_season,Previous_carries_pg,Previous_rushing_yards_pg,Previous_rushing_tds_pg,Previous_rushing_fumbles_pg,Previous_rushing_fumbles_lost_pg,Previous_rushing_first_downs_pg,Previous_rushing_2pt_conversions_pg,Previous_rushing_10_pg,Previous_rushing_12_pg,Previous_rushing_20_pg,Previous_rushing_40_pg,Previous_rushing_epa_pg,Previous_receptions_pg,Previous_targets_pg,Previous_receiving_yards_pg,Previous_receiving_tds_pg,Previous_receiving_fumbles_pg,Previous_receiving_fumbles_lost_pg,Previous_receiving_air_yards_pg,Previous_receiving_yards_after_catch_pg,Previous_receiving_first_downs_pg,Previous_receiving_2pt_conversions_pg,Previous_receiving_10_pg,Previous_receiving_16_pg,Previous_receiving_20_pg,Previous_receiving_40_pg,Previous_air_yards_share_pg,Previous_wopr_pg,Previous_special_teams_tds_pg,Previous_punt_returns_pg,Previous_punt_return_yards_pg,Previous_kickoff_returns_pg,Previous_kickoff_return_yards_pg,Previous_fantasy_points_ppr_pg,Previous_games_played,QB_player_display_name,QB_season,QB_completions_pg,QB_attempts_pg,QB_passing_yards_pg,QB_passing_tds_pg,QB_passing_interceptions_pg,QB_sacks_suffered_pg,QB_sack_yards_lost_pg,QB_sack_fumbles_pg,QB_sack_fumbles_lost_pg,QB_passing_air_yards_pg,QB_passing_yards_after_catch_pg,QB_passing_first_downs_pg,QB_passing_2pt_conversions_pg,QB_passing_10_pg,QB_passing_16_pg,QB_passing_20_pg,QB_passing_40_pg,QB_passing_epa_pg,QB_passing_cpoe_pg,QB_fantasy_points_ppr_pg,QB_games_played,Teammate_player_display_name,Teammate_season,Teammate_carries_pg,Teammate_rushing_yards_pg,Teammate_rushing_tds_pg,Teammate_rushing_fumbles_pg,Teammate_rushing_fumbles_lost_pg,Teammate_rushing_first_downs_pg,Teammate_rushing_2pt_conversions_pg,Teammate_rushing_10_pg,Teammate_rushing_12_pg,Teammate_rushing_20_pg,Teammate_rushing_40_pg,Teammate_rushing_epa_pg,Teammate_receptions_pg,Teammate_targets_pg,Teammate_receiving_yards_pg,Teammate_receiving_tds_pg,Teammate_receiving_fumbles_pg,Teammate_receiving_fumbles_lost_pg,Teammate_receiving_air_yards_pg,Teammate_receiving_yards_after_catch_pg,Teammate_receiving_first_downs_pg,Teammate_receiving_2pt_conversions_pg,Teammate_receiving_10_pg,Teammate_receiving_16_pg,Teammate_receiving_20_pg,Teammate_receiving_40_pg,Teammate_air_yards_share_pg,Teammate_wopr_pg,Teammate_special_teams_tds_pg,Teammate_punt_returns_pg,Teammate_punt_return_yards_pg,Teammate_kickoff_returns_pg,Teammate_kickoff_return_yards_pg,Teammate_fantasy_points_ppr_pg,Teammate_games_played
44,45,Damien Williams,2021,2020,28,CHI,Andy Dalton,2020,34,David Montgomery,2020,24,Damien Williams,5.058333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Andy Dalton,2020.0,19.636364,30.272727,197.272727,1.272727,0.727273,2.181818,-16.727273,0.090909,0.000000,208.090909,94.818182,10.545455,0.000000,7.818182,2.818182,1.818182,0.454545,-1.018261,0.032265,12.445455,11.0,David Montgomery,2020.0,16.466667,71.333333,0.533333,0.000000,0.000000,3.933333,0.066667,1.600000,0.800000,0.333333,0.133333,-0.600822,3.6,4.533333,29.200000,0.133333,0.066667,0.066667,4.266667,26.4,1.666667,0.0,1.333333,0.466667,0.133333,0.0,0.012908,0.188074,0.0,0.0,0.0,0.0,0.000000,17.653333,15.0
117,29,Odell Beckham,2023,2022,30,BAL,Lamar Jackson,2022,26,Gus Edwards,2022,28,Odell Beckham,7.678571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lamar Jackson,2022.0,13.533333,21.733333,149.466667,1.133333,0.466667,1.733333,-7.600000,0.066667,0.066667,183.600000,64.933333,7.000000,0.066667,6.266667,3.200000,1.600000,0.266667,0.873361,-1.451075,15.738667,15.0,Gus Edwards,2022.0,9.666667,48.111111,0.333333,0.111111,0.111111,3.333333,0.000000,1.444444,0.888889,0.333333,0.000000,-0.003327,0.0,0.222222,0.000000,0.000000,0.000000,0.000000,0.666667,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.003796,0.018630,0.0,0.0,0.0,0.0,0.000000,6.588889,9.0
247,36,Jonathon Brooks,2026,2025,23,CAR,Bryce Young,2025,25,Chuba Hubbard,2025,27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bryce Young,2025.0,19.000000,29.875000,188.187500,1.437500,0.687500,1.687500,-12.625000,0.187500,0.125000,193.875000,96.187500,9.562500,0.062500,7.125000,3.437500,2.437500,0.250000,-1.373307,1.271870,13.627500,16.0,Chuba Hubbard,2025.0,8.933333,34.066667,0.066667,0.066667,0.066667,2.066667,0.000000,0.533333,0.066667,0.000000,0.000000,-1.044958,2.0,2.600000,14.866667,0.200000,0.000000,0.000000,-2.666667,19.4,0.800000,0.0,0.466667,0.266667,0.200000,0.0,-0.034977,0.107865,0.0,0.0,0.0,0.6,15.533333,8.360000,15.0

In [129]:
final_rb = final_rb[
    ~(final_rb["player_display_name"].isna() & (final_rb["season"] < 2026))
    & final_rb["Previous_player_display_name"].notna()
    & final_rb["Teammate_player_display_name"].notna()
    & final_rb["QB_player_display_name"].notna()
].copy()

The code above removed players that did not play in the previous season, or players whose teammates did not play in the previous season. Unlike the WRs, a team has less depth at RB, so I did not want to update a player's best teammate to someone who had no production, which could materially throw off projections.

In [130]:
final_rb[final_rb["player_display_name"].isna()]

,preseason_rank,player_name,season,past_season,player_age,team,team_qb,team_qb_season,team_qb_age,teammate,teammate_season,teammate_age,player_display_name,fantasy_points_ppr_pg,Previous_player_display_name,Previous_season,Previous_carries_pg,Previous_rushing_yards_pg,Previous_rushing_tds_pg,Previous_rushing_fumbles_pg,Previous_rushing_fumbles_lost_pg,Previous_rushing_first_downs_pg,Previous_rushing_2pt_conversions_pg,Previous_rushing_10_pg,Previous_rushing_12_pg,Previous_rushing_20_pg,Previous_rushing_40_pg,Previous_rushing_epa_pg,Previous_receptions_pg,Previous_targets_pg,Previous_receiving_yards_pg,Previous_receiving_tds_pg,Previous_receiving_fumbles_pg,Previous_receiving_fumbles_lost_pg,Previous_receiving_air_yards_pg,Previous_receiving_yards_after_catch_pg,Previous_receiving_first_downs_pg,Previous_receiving_2pt_conversions_pg,Previous_receiving_10_pg,Previous_receiving_16_pg,Previous_receiving_20_pg,Previous_receiving_40_pg,Previous_air_yards_share_pg,Previous_wopr_pg,Previous_special_teams_tds_pg,Previous_punt_returns_pg,Previous_punt_return_yards_pg,Previous_kickoff_returns_pg,Previous_kickoff_return_yards_pg,Previous_fantasy_points_ppr_pg,Previous_games_played,QB_player_display_name,QB_season,QB_completions_pg,QB_attempts_pg,QB_passing_yards_pg,QB_passing_tds_pg,QB_passing_interceptions_pg,QB_sacks_suffered_pg,QB_sack_yards_lost_pg,QB_sack_fumbles_pg,QB_sack_fumbles_lost_pg,QB_passing_air_yards_pg,QB_passing_yards_after_catch_pg,QB_passing_first_downs_pg,QB_passing_2pt_conversions_pg,QB_passing_10_pg,QB_passing_16_pg,QB_passing_20_pg,QB_passing_40_pg,QB_passing_epa_pg,QB_passing_cpoe_pg,QB_fantasy_points_ppr_pg,QB_games_played,Teammate_player_display_name,Teammate_season,Teammate_carries_pg,Teammate_rushing_yards_pg,Teammate_rushing_tds_pg,Teammate_rushing_fumbles_pg,Teammate_rushing_fumbles_lost_pg,Teammate_rushing_first_downs_pg,Teammate_rushing_2pt_conversions_pg,Teammate_rushing_10_pg,Teammate_rushing_12_pg,Teammate_rushing_20_pg,Teammate_rushing_40_pg,Teammate_rushing_epa_pg,Teammate_receptions_pg,Teammate_targets_pg,Teammate_receiving_yards_pg,Teammate_receiving_tds_pg,Teammate_receiving_fumbles_pg,Teammate_receiving_fumbles_lost_pg,Teammate_receiving_air_yards_pg,Teammate_receiving_yards_after_catch_pg,Teammate_receiving_first_downs_pg,Teammate_receiving_2pt_conversions_pg,Teammate_receiving_10_pg,Teammate_receiving_16_pg,Teammate_receiving_20_pg,Teammate_receiving_40_pg,Teammate_air_yards_share_pg,Teammate_wopr_pg,Teammate_special_teams_tds_pg,Teammate_punt_returns_pg,Teammate_punt_return_yards_pg,Teammate_kickoff_returns_pg,Teammate_kickoff_return_yards_pg,Teammate_fantasy_points_ppr_pg,Teammate_games_played
212,1,Jahmyr Gibbs,2026,2025,24,DET,Jared Goff,2025,31,Isiah Pacheco,2025,27,NaN,NaN,Jahmyr Gibbs,2025.0,14.294118,71.941176,0.764706,0.117647,0.058824,3.294118,0.000000,1.588235,1.235294,0.588235,0.352941,-0.156885,4.529412,5.529412,36.235294,0.294118,0.000000,0.000000,3.176471,36.176471,1.647059,0.000000,1.352941,0.588235,0.411765,0.058824,0.014739,0.252620,0.000000,0.000000,0.000000,0.000000,0.000000,21.582353,17.0,Jared Goff,2025.0,23.117647,34.000000,268.470588,2.000000,0.470588,2.235294,-15.235294,0.176471,0.176471,218.529412,142.470588,13.117647,0.000000,10.882353,5.941176,3.882353,0.470588,6.262362,2.889624,17.474118,17.0,Isiah Pacheco,2025.0,9.076923,35.538462,0.076923,0.000000,0.000000,2.076923,0.000000,0.769231,0.307692,0.000000,0.000000,-1.049492,1.461538,2.000000,7.769231,0.076923,0.000000,0.000000,-2.076923,9.307692,0.307692,0.000000,0.230769,0.076923,0.076923,0.000000,-0.006067,0.097735,0.000000,0.000000,0.000000,0.000000,0.000000,6.715385,13.0
213,2,Bijan Robinson,2026,2025,24,ATL,Michael Penix,2025,26,Brian Robinson,2025,27,NaN,NaN,Bijan Robinson,2025.0,16.882353,86.941176,0.411765,0.176471,0.117647,3.705882,0.058824,2.117647,1.411765,0.470588,0.117647,-0.720861,4.647059,6.058824,48.235294,0.235294,0.058824,0.058824,5.941176,50.411765,2.000000,0.000000,1.588235,0.764706,0.588235,0.235294,0.021028,0.311127,0.000000,0.000000,0.000000,0.000000,0.000000,21.811765,17.0,Michael Penix,2025.0,18.444444,30.666667,220.222222,1.000000,0.333333,1.444444,-11.222222,0.333333,0.222222,255.555556,98.666667,11.000000,0.111111,9.666667,4.666667,2.888889,0.555556,0.571099,-2.522254,13.364444,9.0,Brian Robinson,2025.0,5.411765,23.529412,0.117647,0.000000,0.000000,1.176471,0.000000,0.588235,0.352941,0.000000,0.000000,-0.047974,0.470588,0.705882,1.470588,0.000000,0.000000,0.000000,0.000000,2.058824,0.058824,0.000000,0.000000,0.000000,0.000000,0.000000,-0.000047,0.031288,0.000000,0.000000,0.000000,0.764706,22.235294,3.676471,17.0
214,3,Christian McCaffrey,2026,2025,30,SF,Brock Purdy,2025,26,Isaac Guerendo,2025,25,NaN,NaN,Christian McCaffrey,2025.0,18.294118,70.705882,0.588235,0.058824,0.000000,4.176471,0.000000,1.588235,1.176471,0.176471,0.058824,-1.238285,6.000000,7.588235,54.352941,0.411765,0.058824,0.000000,19.705882,42.352941,2.823529,0.000000,2.000000,0.764706,0.411765,0.000000,0.078011,0.404912,0.000000,0.000000,0.000000,0.000000,0.000000,24.505882,17.0,Brock Purdy,2025.0,21.888889,31.555556,240.777778,2.222222,1.111111,1.222222,-5.888889,0.333333,0.222222,239.777778,94.333333,14.444444,0.111111,10.777778,4.777778,3.666667,0.111111,7.014438,7.685326,19.708889,9.0,Isaac Guerendo,2025.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.714286,14.285714,0.000000,7.0
215,4,Jonathan Taylor,2026,2025,27,IND,Daniel Jones,2025,29,DJ Giddens,2025,22,NaN,NaN,Jonathan Taylor,2025.0,19.000000,93.235294,1.058824,0.058824,0.058824,4.941176,0.058824,2.117647,1.529412,0.529412,0.235294,1.104214,2.705882,3.235294,22.235294,0.117647,0.058824,0.000000,-2.647059,25.529412,0.882353,0.000000,0.705882,0.411765,0.176471,0.058824,-0.011161,0.156866,0.000000,0.000000,0.000000,0.000000,0.000000,21.311765,17.0,Daniel Jones,2025.0,20.076923,29.538462,238.538462,1.461538,0.615385,1.692308,-12.153846,0.461538,0.230769,236.384615,103.923077,11.461538,0.076923,9.615385,5.153846,2.769231,0.538462,5.019655,2.603710,17.418462,13.0,DJ Giddens,2025.0,5.200000,19.200000,0.000000,0.000000,0.000000,1.000000,0.000000,0.400000,0.200000,0.000000,0.000000,0.005108,0.000000,0.400000,0.000000,0.000000,0.000000,0.000000,-1.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.003647,0.016215,0.000000,0.000000,0.000000,0.000000,0.000000,1.920000,5.0
216,5,Ashton Jeanty,2026,2025,23,LV,Kirk Cousins,2025,38,Dylan Laube,2025,27,NaN,NaN,Ashton Jeanty,2025.0,15.647059,57.352941,0.294118,0.058824,0.058824,2.588235,0.000000,1.411765,0.941176,0.176471,0.117647,-3.834179,3.235294,4.294118,20.352941,0.294118,0.058824,0.000000,-6.117647,26.588235,0.764706,0.000000,0.588235,0.176471,0.176471,0.058824,-0.058067,0.180747,0.000000,0.000000,0.000000,0.000000,0.000000,14.417647,17.0,Kirk Cousins,2025.0,16.600000,26.900000,172.100000,1.000000,0.500000,1.300000,-7.900000,0.200000,0.000000,187.000000,98.300000,8.600000,0.000000,6.900000,3.300000,2.100000,0.300000,-0.093080,-4.495782,10.354000,10.0,Dylan Laube,2025.0,0.411765,0.529412,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.789264,0.176471,0.235294,1.058824,0.000000,0.000000,0.000000,-0.352941,1.411765,0.058824,0.000000,0.058824,0.000000,0.000000,0.000000,-0.004067,0.009716,0.000000,0.000000,0.000000,1.941176,50.294118,0.335294,17.0
217,6,De'Von Achane,2026,2025,25,MIA,Malik Willis,2025,28,Ollie Gordon,2025,22,NaN,NaN,De'Von Achane,2025.0,14.875000,84.375000,0.500000,0.062500,0.000000,3.500000,0.000000,2.500000,2.000000,0.812500,0.250000,0.877428,4.187500,5.312500,30.500000,0.250000,0.000000,0.000000,2.187500,34.500000,1.437500,0.000000,1.250000,0.500000,0.250000,0.000000,0.010673,0.288745,0.000000,0.000000,0.000000,0.000000,0.000000,20.175000,16.0,Malik Willis,2025.0,7.500000,8.750000,105.500000,0.750000,0.000000,0.750000,-3.750000,0.000000,0.000000,88.500000,31.500000,4.750000,0.000000,3.500000,2.250000,2.250000,0.250000,7.021106,24.975325,12.795000,4.0,Ollie Gordon,2025.0,4.117647,11.705882,0.176471,0.000000,0.000000,1.235294,0.000000,0.294118,0.235294,0.058824,0.000000,-0.598199,0.411765,0.529412,1.882353,0.058824,0.000000,0.000000,-1.470588,3.352941,0.058824,0.000000,0.058824,0.058824,0.058824,0.000000,-0.007543,0.022006,0.000000,0.000000,0.000000,0.058824,1.470588,3.182353,17.0
218,7,Chase Brown,2026,2025,26,CIN,Joe Burrow,2025,29,Samaje Perine,2025,31,NaN,NaN,Chase Brown,2025.0,13.647059,59.941176,0.352941,0.058824,0.000000,3.058824,0.000000,1.411765,1.117647,0.352941,0.000000,-0.249492,4.058824,5.176471,25.705882,0.294118,0.058824,0.000000,2.705882,26.470588,1.058824,0.058824,0.823529,0.352941,0.117647,0.000000,0.013669,0.224425,0.000000,0.000000,0.000000,0.000000,0.000000,16.623529,17.0,Joe Burrow,2025.0,21.625000,32.375000,226.125000,2.125000,0.625000,2.125000,-14.125000,0.000000,0.000000,233.500000,103.000000,12.500000,0.000000,9.625000,3.750000,2.750000,0.125000,4.575887,4.629599,16.807500,8.0,Samaje Perine,2025.0,5.600000,25.466667,0.200000,0.200000,0.133333,2.133333,0.000000,0.600000,0.333333,0.133333,0.000000,-0.019160,1.133333,1.400000,5.800000,0.000000,0.000000,0.000000,-2.133333,7.266667,0.333333,0.000000,0.066667,0.066667,0.000000,0.000000,-0.009352,0.055560,0.000000,0.000000,0.000000,1.133333,28.666667,5.193333,15.0
219,8,James Cook,2026,2025,26,BUF,Josh Allen,2025,30,Ray Davis,2025,26,NaN,NaN,James Cook,2025.0,18.176471,95.352941,0.705882,0.352941,0.176471,4.000000,0.000000,2.294118,1.588235,0.529412,0.235294,0.327999,1.941176,2.352941,17.117647,0.117647,0.000000,0.000000,3.294118,16.000000,0.647059,0.000000,0.588235,0.411765,0.235294,0.058824,0.005521,0.126648,0.000000,0.000000,0.000000,0.000000,0.000000,17.776471,17.0,Josh Allen,2025.0,19.937500,28.750000,229.250000,1.562500,0.625000,2.500000,-18.625000,0.062500,0.062500,209.937500,122.625000,11.062500,0.062500,8.812500,5.062500,3.500000,0.625000,4.457896,2.891376,22.788750,16.0,Ray Davis,2025.0,3.411765,16.176471,0.000000,0.000000,0.000000,0.882353,0.000000,0.529412,0.470588,0.058824,0.000000,0.135054,0.588235,0.764706,5.058824,0.117647,0.000000,0.000000,0.058824,5.823529,0.411765,0.000000,0.294118,0.117647,0.058824,0.000000,0.003589,0.045063,0.058824,0.000000,0.000000,1.823529,55.470588,3.770588,17.0
220,9,Derrick Henry,2026,2025,32,BAL,Lamar Jackson,2025,29,Justice Hill,2025,27,NaN,NaN,Derrick Henry,2025.0,18.058824,93.823529,0.941176,0.235294,0.176471,4.647059,0.000000,2.117647,1.764706,1.000000,0.235294,0.539187,0.882353,1.235294,8.823529,0.000000,0.000000,0.000000,0.705882,7.941176,0.235294,0.000000,0.294118,0.117647,0.058824,0.058824,0.002375,0.074870,0.000000,0.000000,0.000000,0.000000,0.000000,16.441176,17.0,Lamar Jackson,2025.0,14.769231,23.230769,196.076923,1.615385,0.538462,2.769231,-18.384615,0.384615,0.230769,203.692308,81.846154,8.384615,0.076923,7.461538,4.384615,2.923077,0.461538,1.396694,2.905986,16.527692,13.0,Justice Hill,2025.0,1.800000,9.300000,0.200000,0.100000,0.000000,0.400000,0.000000,0.100000,0.100000,0.100000,0.100000,-0.156789,2.100000,2.700000,16.900000,0.100000,0.000000,0.000000,-0.600000,18.400000,0.600000,0.000000,0.600000,0.100000,0.100000,0.000000,-0.006439,0.145665,0.000000,0.000000,0.000000,0.700000,18.800000,6.520000,10.0
221,10,Saquon Barkley,2026,2025,29,PHI,Jalen Hurts,2025,28,Tank Bigsby,2025,24,NaN,NaN,Saquon Barkley,2025.0,17.500000,71.250000,0.437500,0.000000,0.000000,3.000000,0.062500,1.750000,1.250000,0.250000,0.187500,-1.506036,2.312500,3.125000,17.062500,0.125000,0.062500,0.062500,1.937500,18.500000,0.687500,0.000000,0.562500,0.187500,0.125000,0.125000,-0.006874,0.175989,0.000000,0.000000,0.000000,0.000000,0.000000,14.518750,16.0,Jalen Hurts,2025.0,18.375000,28.375000,201.500000,1.562500,0.375000,2.000000,-11.312500,0.187500,0.062500,254.500000,79.062500,9.375000,0.000000,7.312500,4.187500,2.500000,0.562500,2.144653,4.227860,18.816250,16.0,Tank Bigsby,2025.0,4.200000,23.733333,0.133333,0.000000,0.000000,1.200000,0.000000,0.866667,0.666667,0.133333,0.000000,0.659020,0.200000,0.266667,2.133333,0.000000,0.000000,0.000000,-0.400000,2.600000,0.066667,0.000000,0.066667,0.066667,0.066667,0.000000,-0.001222,0.016534,0.000000,0.000000,0.000000,0.666667,13.800000,3.586667,15.0
222,11,Omarion Hampton,2026,2025,21,LAC,Justin Herbert,2025,28,Kimani Vidal,2025,24,NaN,NaN,Omarion Hampton,2025.0,13.777778,60.555556,0.444444,0.000000,0.000000,3.444444,0.000000,1.555556,1.000000,0.333333,0.111111,-0.086193,3.555556,3.888889,21.333333,0.111111,0.111111,0.000000,-6.000000,27.222222,0.777778,0.000000,0.888889,0.333333,0.111111,0.000000,-0.029757,0.156244,0.000000,0.000000,0.000000,0.111111,3.333333,15.077778,9.0,Justin Herbert,2025.0,21.250000,32.000000,232.937500,1.625000,0.812500,3.375000,-18.812500,0.187500,0.062500,250.687500,103.562500,10.937500,0.000000,9.000000,4.125000,2.687500,0.500000,1.007163,1.633977,17.930000,16.0,Kimani Vidal,2025.0,11.923077,49.461538,0.230769,0.076923,0.000000,2.461538,0.000000,1.000000,0.692308,0.307692,0.076923,-1.174088,1.230769,1.692308,10.461538,0.076923,0.000000,0.000000,-1.076923,13.076923,0.461538,0.000000,0.384615,0.076923,0.076923,0.076923,-0.006677,0.076628,0.000000,0.000000,0.000000,0.615385,13.615385,9.069231,13.0
223,12,Josh Jacobs,2026,2025,28,GB,Jordan Love,2025,27,Emanuel Wilson,2025,25,NaN,NaN,Josh Jacobs,2025.0,15.600000,61.933333,0.866667,0.200000,0.133333,3.666667,0.000000,1.533333,0.933333,0.200000,0.066667,-0.989066,2.400000,2.933333,18.800000,0.066667,0.000000,0.000000,-2.600000,20.266667,0.533333,0.000000,0.400000,0.266667,0.266667,0.000000,-0.040054,0.124270,0.000000,0.000000,0.000000,0.000000,0.000000,15.806667,15.0,Jordan Love,2025.0,19.400000,29.266667,225.400000,1.533333,0.400000,1.400000,-11.266667,0.133333,0.133333,258.066667,100.733333,10.600000,0.133333,8.533333,5.400000,3.266667,0.533333,7.374086,5.049499,15.676000,15.0,Emanuel Wilson,2025.0,7.352941,29.176471,0.176471,0.000000,0.000000,1.882353,0.000000,0.705882,0.470588,0.000000,0.000000,-0.481869,0.882353,1.000000,5.823529,0.000000,0.058824,0.000000,-1.882353,7.823529,0.294118,0.058824,0.235294,0.058824,0.058824,0.000000,-0.018630,0.042942,0.000000,0.000000,0.000000,0.529412,13.705882,5.558824,17.0
224,13,Kenneth Walker,2026,2025,25,KC,Patrick Mahomes,2025,30,Emari Demercado,2025,25,NaN,NaN,Kenneth Walker,2025.0,13.000000,60.411765,0.294118,0.000000,0.000000,2.705882,0.000000,1.941176,1.294118,0.588235,0.058824,-0.840818,1.823529,2.117647,16.588235,0.000000,0.058824,0.000000,-2.411765,19.941176,0.705882,0.000000,0.705882,0.352941,0.294118,0.058824,-0.021268,0.108992,0.000000,0.000000,0.000000,0.000000,0.000000,11.288235,17.0,Patrick Mahomes,2025.0,22.500000,35.857143,256.214286,1.571429,0.785714,2.428571,-13.785714,0.214286,0.000000,289.285714,135.357143,12.357143,0.142857,10.428571,5.142857,3.500000,0.571429,4.874781,0.137742,20.405714,14.0,Emari Demercado,2025.0,3.666667,26.000000,0.000000,0.083333,0.083333,0.750000,0.000000,0.750000,0.500000,0.166667,0.166667,-0.627402,1.083333,1.666667,8.416667,0.083333,0.000000,0.000000,1.000000,7.000000,0.250000,0.000000,0.166667,0.166667,0.166667,0.000000,0.004569,0.068057,0.000000,0.000000,0.000000,0.250000,7.166667,4.858333,12.0
225,14,Breece Hall,2026,2025,25,NYJ,Geno Smith,2025,35,Braelon Allen,2025,22,NaN,NaN,Breece Hall,2025.0,15.187500,66.562500,0.250000,0.125000,0.125000,3.562500,0.000000,1.625000,1.312500,0.500000,0.062500,-1.391663,2.250000,3.000000,21.875000,0.062500,0.000000,0.000000,0.875000,20.062500,0.812500,0.000000,0.687500,0.312500,0.250000,0.125000,-0.007494,0.153532,0.000000,0.000000,0.000000,0.000000,0.000000,12.978750,16.0,Geno Smith,2025.0,20.133333,29.866667,201.666667,1.266667,1.133333,3.666667,-27.000000,0.200000,0.066667,184.133333,114.200000,9.866667,0.066667,7.733333,3.533333,2.200000,0.200000,-4.861427,1.279700,11.593333,15.0,Braelon Allen,2025.0,4.500000,19.000000,0.250000,0.250000,0.250000,1.000000,0.000000,0.250000,0.250000,0.000000,0.000000,-2.174898,0.500000,0.750000,4.250000,0.000000,0.000000,0.000000,2.000000,2.250000,0.250000,0.000000,0.250000,0.000000,0.000000,0.000000,0.012422,0.047981,0.000000,0.000000,0.000000,1.000000,25.000000,3.825000,4.0
226,15,Kyren Williams,2026,2025,25,LAR,Matthew Stafford,2025,38,Blake Corum,2025,25,NaN,NaN,Kyren Williams,2025.0,15.235294,73.647059,0.588235,0.117647,0.117647,4.352941,0.000000,1.529412,1.058824,0.352941,0.000000,0.289859,2.117647,2.941176,16.529412,0.176471,0.000000,0.000000,7.352941,9.117647,0.705882,0.000000,0.470588,0.117647,0.117647,0.000000,0.020961,0.135830,0.000000,0.058824,0.470588,0.000000,0.000000,15.488235,17.0,Matthew Stafford,2025.0,22.823529,35.117647,276.882353,2.705882,0.470588,1.352941,-8.823529,0.117647,0.117647,325.176471,108.823529,13.882353,0.000000,10.823529,5.823529,4.235294,0.470588,8.850253,1.674841,20.610588,17.0,Blake Corum,2025.0,8.529412,43.882353,0.352941,0.000000,0.000000,2.588235,0.000000,1.352941,1.000000,0.294118,0.058824,0.936973,0.470588,0.823529,2.117647,0.000000,0.000000,0.000000,1.470588,2.176471,0.117647,0.000000,0.176471,0.000000,0.000000,0.000000,0.000961,0.034601,0.000000,0.000000,0.000000,0.764706,19.176471,7.188235,17.0
227,16,Javonte Williams,2026,2025,26,DAL,Dak Prescott,2025,33,Jaydon Blue,2025,22,NaN,NaN,Javonte Williams,2025.0,15.750000,75.062500,0.687500,0.062500,0.062500,4.187500,0.000000,1.625000,1.062500,0.375000,0.062500,0.762813,2.187500,3.187500,8.562500,0.125000,0.062500,0.062500,-4.187500,12.875000,0.437500,0.000000,0.187500,0.000000,0.000000,0.000000,-0.014613,0.118728,0.000000,0.000000,0.000000,0.000000,0.000000,15.175000,16.0,Dak Prescott,2025.0,23.764706,35.294118,267.764706,1.764706,0.588235,1.823529,-12.235294,0.117647,0.058824,282.882353,119.000000,12.941176,0.176471,10.764706,5.294118,3.117647,0.705882,6.726437,1.826440,18.457647,17.0,Jaydon Blue,2025.0,7.600000,25.800000,0.200000,0.200000,0.000000,1.400000,0.000000,1.000000,0.600000,0.200000,0.000000,-1.497527,0.200000,0.200000,1.000000,0.000000,0.000000,0.000000,-1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.004717,0.006698,0.000000,0.000000,0.000000,0.600000,14.400000,4.080000,5.0
228,17,Travis Etienne,2026,2025,27,NO,Tyler Shough,2025,26,Alvin Kamara,2025,31,NaN,NaN,Travis Etienne,2025.0,15.294118,65.117647,0.411765,0.000000,0.000000,2.823529,0.000000,1.529412,0.882353,0.411765,0.176471,-1.116638,2.117647,3.058824,17.176471,0.352941,0.000000,0.000000,-4.470588,19.941176,0.823529,0.000000,0.588235,0.176471,0.117647,0.058824,-0.016620,0.134817,0.000000,0.000000,0.000000,0.000000,0.000000,14.935294,17.0,Tyler Shough,2025.0,20.090909,29.727273,216.727273,0.909091,0.545455,2.818182,-17.727273,0.181818,0.090909,246.181818,95.545455,9.727273,0.000000,9.454545,4.090909,1.727273,0.272727,0.187267,-2.748456,14.360000,11.0,Alvin Kamara,2025.0,11.909091,42.818182,0.090909,0.090909,0.090909,1.909091,0.000000,0.909091,0.636364,0.000000,0.000000,-2.615907,3.000000,3.545455,16.909091,0.000000,0.090909,0.090909,3.000000,18.363636,0.636364,0.000000,0.545455,0.181818,0.181818,0.000000,0.007683,0.180409,0.000000,0.000000,0.000000,0.000000,0.000000,9.154545,11.0

In [132]:
cols = [
    "QB_passing_cpoe_pg",
    "Teammate_rushing_epa_pg"
]

final_rb[cols] = final_rb[cols].fillna(0)

Imputes a zero for any final null values.

In [133]:
final_rb.isnull().sum()

preseason_rank                              0
player_name                                 0
season                                      0
past_season                                 0
player_age                                  0
team                                        0
team_qb                                     0
team_qb_season                              0
team_qb_age                                 0
teammate                                    0
teammate_season                             0
teammate_age                                0
player_display_name                        51
fantasy_points_ppr_pg                      51
Previous_player_display_name                0
Previous_season                             0
Previous_carries_pg                         0
Previous_rushing_yards_pg                   0
Previous_rushing_tds_pg                     0
Previous_rushing_fumbles_pg                 0
Previous_rushing_fumbles_lost_pg            0
Previous_rushing_first_downs_pg             0
Previous_rushing_2pt_conversions_pg         0
Previous_rushing_10_pg                      0
Previous_rushing_12_pg                      0
Previous_rushing_20_pg                      0
Previous_rushing_40_pg                      0
Previous_rushing_epa_pg                     0
Previous_receptions_pg                      0
Previous_targets_pg                         0
Previous_receiving_yards_pg                 0
Previous_receiving_tds_pg                   0
Previous_receiving_fumbles_pg               0
Previous_receiving_fumbles_lost_pg          0
Previous_receiving_air_yards_pg             0
Previous_receiving_yards_after_catch_pg     0
Previous_receiving_first_downs_pg           0
Previous_receiving_2pt_conversions_pg       0
Previous_receiving_10_pg                    0
Previous_receiving_16_pg                    0
Previous_receiving_20_pg                    0
Previous_receiving_40_pg                    0
Previous_air_yards_share_pg                 0
Previous_wopr_pg                            0
Previous_special_teams_tds_pg               0
Previous_punt_returns_pg                    0
Previous_punt_return_yards_pg               0
Previous_kickoff_returns_pg                 0
Previous_kickoff_return_yards_pg            0
Previous_fantasy_points_ppr_pg              0
Previous_games_played                       0
QB_player_display_name                      0
QB_season                                   0
QB_completions_pg                           0
QB_attempts_pg                              0
QB_passing_yards_pg                         0
QB_passing_tds_pg                           0
QB_passing_interceptions_pg                 0
QB_sacks_suffered_pg                        0
QB_sack_yards_lost_pg                       0
QB_sack_fumbles_pg                          0
QB_sack_fumbles_lost_pg                     0
QB_passing_air_yards_pg                     0
QB_passing_yards_after_catch_pg             0
QB_passing_first_downs_pg                   0
QB_passing_2pt_conversions_pg               0
QB_passing_10_pg                            0
QB_passing_16_pg                            0
QB_passing_20_pg                            0
QB_passing_40_pg                            0
QB_passing_epa_pg                           0
QB_passing_cpoe_pg                          0
QB_fantasy_points_ppr_pg                    0
QB_games_played                             0
Teammate_player_display_name                0
Teammate_season                             0
Teammate_carries_pg                         0
Teammate_rushing_yards_pg                   0
Teammate_rushing_tds_pg                     0
Teammate_rushing_fumbles_pg                 0
Teammate_rushing_fumbles_lost_pg            0
Teammate_rushing_first_downs_pg             0
Teammate_rushing_2pt_conversions_pg         0
Teammate_rushing_10_pg                      0
Teammate_rushing_12_pg                      0
Teammate_rushing_20_pg                      0
Teammate_rushing_40_pg                      0
Teammate_rushing_epa_pg                     0
Teammate_receptions_pg                      0
Teammate_targets_pg                         0
Teammate_receiving_yards_pg                 0
Teammate_receiving_tds_pg                   0
Teammate_receiving_fumbles_pg               0
Teammate_receiving_fumbles_lost_pg          0
Teammate_receiving_air_yards_pg             0
Teammate_receiving_yards_after_catch_pg     0
Teammate_receiving_first_downs_pg           0
Teammate_receiving_2pt_conversions_pg       0
Teammate_receiving_10_pg                    0
Teammate_receiving_16_pg                    0
Teammate_receiving_20_pg                    0
Teammate_receiving_40_pg                    0
Teammate_air_yards_share_pg                 0
Teammate_wopr_pg                            0
Teammate_special_teams_tds_pg               0
Teammate_punt_returns_pg                    0
Teammate_punt_return_yards_pg               0
Teammate_kickoff_returns_pg                 0
Teammate_kickoff_return_yards_pg            0
Teammate_fantasy_points_ppr_pg              0
Teammate_games_played                       0
dtype: int64

The remaining nulls are just 2026 players that we don't know the result for yet in terms of PPR fantasy points per game.

### Final Cleaned Dataset

In [134]:
final_rb.to_csv('../outputs/final_rbs_model_data_2020_2026.csv', index=False)